import JJMath.Manifold.AnnularCohomology
import JJMath.Manifold.DeRhamMayerVietorisLinear

/-!
# The first de Rham cohomology of an annular cylinder

Two punctured-cylinder charts cover the cylinder. Their overlap has two
components, so its degree-zero cohomology is generated by a constant and a
locally constant step function. Mayer--Vietoris then shows that first de Rham
cohomology of the cylinder is generated by the connecting class of that step
function.
-/

open Set
open scoped Manifold ContDiff Topology

namespace JJMath.Manifold

noncomputable section

attribute [local instance] finrank_real_complex_fact'

theorem deRhamCohomologyPullbackDiffeomorph_constant
    {E₁ H₁ M₁ E₂ H₂ M₂ : Type*}
    [NormedAddCommGroup E₁] [NormedSpace ℝ E₁]
    [NormedAddCommGroup E₂] [NormedSpace ℝ E₂]
    [TopologicalSpace H₁] [TopologicalSpace M₁] [ChartedSpace H₁ M₁]
    [TopologicalSpace H₂] [TopologicalSpace M₂] [ChartedSpace H₂ M₂]
    (I₁ : ModelWithCorners ℝ E₁ H₁) (I₂ : ModelWithCorners ℝ E₂ H₂)
    [IsManifold I₁ ∞ M₁] [IsManifold I₂ ∞ M₂]
    (phi : M₁ ≃ₘ⟮I₁, I₂⟯ M₂) (c : ℝ) :
    deRhamCohomologyPullbackDiffeomorph I₁ I₂ phi 0
        (deRhamConstantH0Class (I0 := I₂) (M0 := M₂) c) =
      deRhamConstantH0Class (I0 := I₁) (M0 := M₁) c := by
  simp only [deRhamConstantH0Class, deRhamCohomologyPullbackDiffeomorph]
  apply congrArg
    (DeRhamExactClosedForms (I := I₁) (M := M₁) (A := ℝ) 0).mkQ
  apply Subtype.ext
  apply DifferentialForm.ext
  intro x
  ext v
  rfl

theorem deRhamH0_eq_constant_of_diffeomorphic_convex
    {E₁ H₁ M₁ E₂ : Type*}
    [NormedAddCommGroup E₁] [NormedSpace ℝ E₁]
    [NormedAddCommGroup E₂] [NormedSpace ℝ E₂] [FiniteDimensional ℝ E₂]
    [TopologicalSpace H₁] [TopologicalSpace M₁] [ChartedSpace H₁ M₁]
    (I₁ : ModelWithCorners ℝ E₁ H₁) [IsManifold I₁ ∞ M₁]
    (V : TopologicalSpace.Opens E₂) (hconvex : Convex ℝ (V : Set E₂))
    (x₀ : V) (phi : M₁ ≃ₘ⟮I₁, 𝓘(ℝ, E₂)⟯ V)
    (alpha : DeRhamCohomology (I := I₁) (M := M₁) (A := ℝ) 0) :
    ∃ c : ℝ,
      alpha = deRhamConstantH0Class (I0 := I₁) (M0 := M₁) c := by
  let beta := deRhamCohomologyPullbackDiffeomorph
    (𝓘(ℝ, E₂)) I₁ phi.symm 0 alpha
  rcases deRham_convex_open_H0_eq_constant V hconvex x₀ beta with ⟨c, hc⟩
  refine ⟨c, ?_⟩
  calc
    alpha = deRhamCohomologyPullbackDiffeomorph I₁ (𝓘(ℝ, E₂)) phi 0 beta :=
      (deRhamCohomologyPullbackDiffeomorph_comp_symm
        I₁ (𝓘(ℝ, E₂)) phi 0 alpha).symm
    _ = deRhamCohomologyPullbackDiffeomorph I₁ (𝓘(ℝ, E₂)) phi 0
          (deRhamConstantH0Class (I0 := 𝓘(ℝ, E₂)) (M0 := V) c) :=
      congrArg _ hc
    _ = deRhamConstantH0Class (I0 := I₁) (M0 := M₁) c :=
      deRhamCohomologyPullbackDiffeomorph_constant I₁ (𝓘(ℝ, E₂)) phi c

private noncomputable def legacySmoothRealFunctionOfIsLocallyConstant
    {E H M : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    [TopologicalSpace H] [TopologicalSpace M] [ChartedSpace H M]
    (I : ModelWithCorners ℝ E H) [IsManifold I ∞ M]
    (f : M → ℝ) (hf : IsLocallyConstant f) : C^∞⟮I, M; ℝ⟯ where
  val := f
  property := by
    intro x
    exact contMDiffAt_const.congr_of_eventuallyEq (hf.eventually_eq x)

private theorem legacyDeRhamDifferential_locallyConstant_zeroForm_eq_zero
    {E H M : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    [TopologicalSpace H] [TopologicalSpace M] [ChartedSpace H M]
    (I : ModelWithCorners ℝ E H) [IsManifold I ∞ M]
    (f : M → ℝ) (hf : IsLocallyConstant f) :
    deRhamDifferential (I := I) (M := M) (A := ℝ) 0
        (smoothRealFunctionToZeroForm (I0 := I)
          (smoothRealFunctionOfIsLocallyConstant I f hf)) = 0 := by
  apply DifferentialForm.ext
  intro x
  have heq : ∀ᶠ y in 𝓝 x,
      (smoothRealFunctionToZeroForm (I0 := I)
        (smoothRealFunctionOfIsLocallyConstant I f hf)).toFun y =
      (smoothRealFunctionToZeroForm (I0 := I)
        (smoothRealConstantFunction (I0 := I) (f x))).toFun y := by
    filter_upwards [hf.eventually_eq x] with y hy
    simp [smoothRealFunctionOfIsLocallyConstant, hy]
  rw [deRhamDifferential_toFun_eq_of_eventuallyEq
    (I := I)
    (smoothRealFunctionToZeroForm (I0 := I)
      (smoothRealFunctionOfIsLocallyConstant I f hf))
    (smoothRealFunctionToZeroForm (I0 := I)
      (smoothRealConstantFunction (I0 := I) (f x))) heq]
  rw [deRhamDifferential_smoothRealFunctionToZeroForm_const]

theorem deRhamH0_mkQ_eq_iff
    {E H M : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    [TopologicalSpace H] [TopologicalSpace M] [ChartedSpace H M]
    (I : ModelWithCorners ℝ E H) [IsManifold I ∞ M]
    (omega eta : DeRhamClosedForms (I := I) (M := M) (A := ℝ) 0) :
    (DeRhamExactClosedForms (I := I) (M := M) (A := ℝ) 0).mkQ omega =
        (DeRhamExactClosedForms (I := I) (M := M) (A := ℝ) 0).mkQ eta ↔
      omega = eta := by
  simp only [Submodule.mkQ_apply]
  rw [Submodule.Quotient.eq]
  simp [DeRhamExactClosedForms, DeRhamExactForms, sub_eq_zero]

set_option synthInstance.maxHeartbeats 100000 in
theorem deRhamConstantH0Class_sub
    {E H M : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    [TopologicalSpace H] [TopologicalSpace M] [ChartedSpace H M]
    (I : ModelWithCorners ℝ E H) [IsManifold I ∞ M]
    (c d : ℝ) :
    deRhamConstantH0Class (I0 := I) (M0 := M) c -
        deRhamConstantH0Class (I0 := I) (M0 := M) d =
      deRhamConstantH0Class (I0 := I) (M0 := M) (c - d) := by
  simp only [deRhamConstantH0Class, ← map_sub]
  apply congrArg
    (DeRhamExactClosedForms (I := I) (M := M) (A := ℝ) 0).mkQ
  apply Subtype.ext
  apply DifferentialForm.ext
  intro x
  ext q
  rw [show q = (fun i : Fin 0 => nomatch i) from Subsingleton.elim _ _]
  simp [deRhamConstantZeroClosedForm, smoothRealFunctionToZeroForm,
    smoothRealConstantFunction]
  change c - d = c - d
  rfl

def annularOpposite (v : Circle) : Circle :=
  (stereographic' 1 v).symm 0

theorem annularOpposite_mem_source (v : Circle) :
    annularOpposite v ∈ (stereographic' 1 v).source := by
  apply (stereographic' 1 v).map_target
  simp

theorem annularPunctureChart_opposite (v : Circle) :
    stereographic' 1 v (annularOpposite v) = 0 := by
  apply (stereographic' 1 v).right_inv
  simp

theorem annularOpposite_ne (v : Circle) : annularOpposite v ≠ v := by
  intro h
  have := annularOpposite_mem_source v
  rw [stereographic'_source] at this
  exact this h

theorem euclideanFinOne_eq_zero_iff
    (x : EuclideanSpace ℝ (Fin 1)) : x = 0 ↔ x 0 = 0 := by
  constructor
  · intro h
    rw [h]
    rfl
  · intro h
    apply WithLp.ofLp_injective
    funext i
    fin_cases i
    exact h

theorem stereographic_eq_zero_iff (v x : Circle)
    (hx : x ∈ (stereographic' 1 v).source) :
    stereographic' 1 v x = 0 ↔ x = annularOpposite v := by
  constructor
  · intro hzero
    apply (stereographic' 1 v).injOn hx (annularOpposite_mem_source v)
    rw [hzero, annularPunctureChart_opposite]
  · intro h
    rw [h, annularPunctureChart_opposite]

def annularPositiveTarget :
    TopologicalSpace.Opens (EuclideanSpace ℝ (Fin 1) × ℝ) where
  carrier := {p | 0 < p.1 0}
  is_open' := isOpen_lt continuous_const
    ((PiLp.continuous_apply 2 (fun _ : Fin 1 => ℝ) 0).comp continuous_fst)

def annularNegativeTarget :
    TopologicalSpace.Opens (EuclideanSpace ℝ (Fin 1) × ℝ) where
  carrier := {p | p.1 0 < 0}
  is_open' := isOpen_lt
    ((PiLp.continuous_apply 2 (fun _ : Fin 1 => ℝ) 0).comp continuous_fst)
    continuous_const

theorem annularPositiveTarget_convex :
    Convex ℝ (annularPositiveTarget : Set (EuclideanSpace ℝ (Fin 1) × ℝ)) := by
  change Convex ℝ {p : EuclideanSpace ℝ (Fin 1) × ℝ | 0 < p.1 0}
  apply convex_halfSpace_gt
  exact ⟨by intro x y; simp, by intro c x; simp⟩

theorem annularNegativeTarget_convex :
    Convex ℝ (annularNegativeTarget : Set (EuclideanSpace ℝ (Fin 1) × ℝ)) := by
  change Convex ℝ {p : EuclideanSpace ℝ (Fin 1) × ℝ | p.1 0 < 0}
  apply convex_halfSpace_lt
  exact ⟨by intro x y; simp, by intro c x; simp⟩

theorem annularPositiveTarget_nonempty :
    (annularPositiveTarget : Set (EuclideanSpace ℝ (Fin 1) × ℝ)).Nonempty := by
  refine ⟨(WithLp.toLp 2 (fun _ : Fin 1 => (1 : ℝ)), 0), ?_⟩
  simp [annularPositiveTarget]

theorem annularNegativeTarget_nonempty :
    (annularNegativeTarget : Set (EuclideanSpace ℝ (Fin 1) × ℝ)).Nonempty := by
  refine ⟨(WithLp.toLp 2 (fun _ : Fin 1 => (-1 : ℝ)), 0), ?_⟩
  simp [annularNegativeTarget]

def annularPositiveComponent (v : Circle) :
    TopologicalSpace.Opens (Circle × ℝ) where
  carrier :=
    (deRham_boundarylessExtendedChart AnnularCylinderModel
      (annularPunctureChart v)).source ∩
      deRham_boundarylessExtendedChart AnnularCylinderModel
        (annularPunctureChart v) ⁻¹' annularPositiveTarget
  is_open' :=
    (deRham_boundarylessExtendedChart AnnularCylinderModel
      (annularPunctureChart v)).isOpen_inter_preimage annularPositiveTarget.2

def annularNegativeComponent (v : Circle) :
    TopologicalSpace.Opens (Circle × ℝ) where
  carrier :=
    (deRham_boundarylessExtendedChart AnnularCylinderModel
      (annularPunctureChart v)).source ∩
      deRham_boundarylessExtendedChart AnnularCylinderModel
        (annularPunctureChart v) ⁻¹' annularNegativeTarget
  is_open' :=
    (deRham_boundarylessExtendedChart AnnularCylinderModel
      (annularPunctureChart v)).isOpen_inter_preimage annularNegativeTarget.2

theorem mem_annularPositiveComponent_iff (v : Circle) (p : Circle × ℝ) :
    p ∈ (annularPositiveComponent v : Set (Circle × ℝ)) ↔
      p.1 ≠ v ∧ 0 < (stereographic' 1 v p.1) 0 := by
  simp only [annularPositiveComponent]
  simp [annularPunctureChart, annularPositiveTarget, AnnularCylinderModel,
    deRham_boundarylessExtendedChart]
  intro hpos
  constructor
  · rintro ⟨hsource, _⟩
    change p.1 ∈ ({v}ᶜ : Set Circle) ∧ p.2 ∈ (Set.univ : Set ℝ) at hsource
    simpa using hsource.1
  · intro hpv
    constructor
    · change p.1 ∈ ({v}ᶜ : Set Circle) ∧ p.2 ∈ (Set.univ : Set ℝ)
      exact ⟨by simpa using hpv, Set.mem_univ _⟩
    · exact Set.mem_univ _

theorem mem_annularNegativeComponent_iff (v : Circle) (p : Circle × ℝ) :
    p ∈ (annularNegativeComponent v : Set (Circle × ℝ)) ↔
      p.1 ≠ v ∧ (stereographic' 1 v p.1) 0 < 0 := by
  simp only [annularNegativeComponent]
  simp [annularPunctureChart, annularNegativeTarget, AnnularCylinderModel,
    deRham_boundarylessExtendedChart]
  intro hneg
  constructor
  · rintro ⟨hsource, _⟩
    change p.1 ∈ ({v}ᶜ : Set Circle) ∧ p.2 ∈ (Set.univ : Set ℝ) at hsource
    simpa using hsource.1
  · intro hpv
    constructor
    · change p.1 ∈ ({v}ᶜ : Set Circle) ∧ p.2 ∈ (Set.univ : Set ℝ)
      exact ⟨by simpa using hpv, Set.mem_univ _⟩
    · exact Set.mem_univ _

theorem mem_annularPunctureOpen_iff (v : Circle) (p : Circle × ℝ) :
    p ∈ (annularPunctureOpen v : Set (Circle × ℝ)) ↔ p.1 ≠ v := by
  simp only [annularPunctureOpen, annularPunctureChart,
    OpenPartialHomeomorph.prod_source, stereographic'_source,
    OpenPartialHomeomorph.refl_source]
  change (p.1 ∈ ({v}ᶜ : Set Circle) ∧ p.2 ∈ (Set.univ : Set ℝ)) ↔ p.1 ≠ v
  simp

def annularDoublePunctureOpen (v : Circle) :
    TopologicalSpace.Opens (Circle × ℝ) :=
  annularPunctureOpen v ⊓ annularPunctureOpen (annularOpposite v)

theorem annularComponents_cover_doublePuncture (v : Circle) :
    annularPositiveComponent v ⊔ annularNegativeComponent v =
      annularDoublePunctureOpen v := by
  apply le_antisymm
  · apply sup_le
    · intro p hp
      have hpSet : p ∈ (annularPositiveComponent v : Set (Circle × ℝ)) := hp
      rw [mem_annularPositiveComponent_iff] at hpSet
      change p ∈ annularPunctureOpen v ∧
        p ∈ annularPunctureOpen (annularOpposite v)
      have hpv : p ∈ annularPunctureOpen v :=
        (mem_annularPunctureOpen_iff v p).mpr hpSet.1
      refine ⟨hpv, ?_⟩
      apply (mem_annularPunctureOpen_iff (annularOpposite v) p).mpr
      intro hopposite
      rw [hopposite, annularPunctureChart_opposite] at hpSet
      have : (0 : ℝ) < 0 := by simpa using hpSet.2
      exact (lt_irrefl 0) this
    · intro p hp
      have hpSet : p ∈ (annularNegativeComponent v : Set (Circle × ℝ)) := hp
      rw [mem_annularNegativeComponent_iff] at hpSet
      change p ∈ annularPunctureOpen v ∧
        p ∈ annularPunctureOpen (annularOpposite v)
      have hpv : p ∈ annularPunctureOpen v :=
        (mem_annularPunctureOpen_iff v p).mpr hpSet.1
      refine ⟨hpv, ?_⟩
      apply (mem_annularPunctureOpen_iff (annularOpposite v) p).mpr
      intro hopposite
      rw [hopposite, annularPunctureChart_opposite] at hpSet
      have : (0 : ℝ) < 0 := by simpa using hpSet.2
      exact (lt_irrefl 0) this
  · intro p hp
    change p ∈ annularPunctureOpen v ∧
      p ∈ annularPunctureOpen (annularOpposite v) at hp
    have hp' : p.1 ≠ v ∧ p.1 ≠ annularOpposite v := by
      exact ⟨(mem_annularPunctureOpen_iff v p).mp hp.1,
        (mem_annularPunctureOpen_iff (annularOpposite v) p).mp hp.2⟩
    change p ∈ annularPositiveComponent v ∨ p ∈ annularNegativeComponent v
    have hsource : p.1 ∈ (stereographic' 1 v).source := by
      simpa [stereographic'_source] using hp'.1
    have hcoord : (stereographic' 1 v p.1) 0 ≠ 0 := by
      intro hzero
      apply hp'.2
      apply (stereographic_eq_zero_iff v p.1 hsource).mp
      exact (euclideanFinOne_eq_zero_iff _).mpr hzero
    rcases lt_or_gt_of_ne hcoord with hneg | hpos
    · right
      show p ∈ (annularNegativeComponent v : Set (Circle × ℝ))
      exact (mem_annularNegativeComponent_iff v p).mpr ⟨hp'.1, hneg⟩
    · left
      show p ∈ (annularPositiveComponent v : Set (Circle × ℝ))
      exact (mem_annularPositiveComponent_iff v p).mpr ⟨hp'.1, hpos⟩

theorem annularComponents_disjoint (v : Circle) :
    annularPositiveComponent v ⊓ annularNegativeComponent v = ⊥ := by
  apply le_antisymm
  · intro p hp
    change p ∈ annularPositiveComponent v ∧ p ∈ annularNegativeComponent v at hp
    have hpPos : p ∈ (annularPositiveComponent v : Set (Circle × ℝ)) := hp.1
    have hpNeg : p ∈ (annularNegativeComponent v : Set (Circle × ℝ)) := hp.2
    rw [mem_annularPositiveComponent_iff] at hpPos
    rw [mem_annularNegativeComponent_iff] at hpNeg
    have : False := by linarith [hpPos.2, hpNeg.2]
    exact this.elim
  · intro p hp
    change p ∈ (∅ : Set (Circle × ℝ)) at hp
    exact hp.elim

theorem annularPositiveComponent_le_doublePuncture (v : Circle) :
    annularPositiveComponent v ≤ annularDoublePunctureOpen v := by
  rw [← annularComponents_cover_doublePuncture v]
  exact le_sup_left

theorem annularNegativeComponent_le_doublePuncture (v : Circle) :
    annularNegativeComponent v ≤ annularDoublePunctureOpen v := by
  rw [← annularComponents_cover_doublePuncture v]
  exact le_sup_right

def annularOverlapPositiveSet (v : Circle) :
    Set (annularDoublePunctureOpen v) :=
  {x | (x.1 : Circle × ℝ) ∈ (annularPositiveComponent v : Set (Circle × ℝ))}

theorem annularOverlapPositiveSet_isClopen (v : Circle) :
    IsClopen (annularOverlapPositiveSet v) := by
  have hopen : IsOpen (annularOverlapPositiveSet v) :=
    (annularPositiveComponent v).2.preimage continuous_subtype_val
  refine ⟨?_, hopen⟩
  rw [← isOpen_compl_iff]
  have heq : (annularOverlapPositiveSet v)ᶜ =
      {x : annularDoublePunctureOpen v |
        (x.1 : Circle × ℝ) ∈
          (annularNegativeComponent v : Set (Circle × ℝ))} := by
    ext x
    change
      (¬(x.1 : Circle × ℝ) ∈
        (annularPositiveComponent v : Set (Circle × ℝ))) ↔
      (x.1 : Circle × ℝ) ∈
        (annularNegativeComponent v : Set (Circle × ℝ))
    rw [mem_annularPositiveComponent_iff,
      mem_annularNegativeComponent_iff]
    have hxpuncture :
        (x.1 : Circle × ℝ).1 ≠ v ∧
          (x.1 : Circle × ℝ).1 ≠ annularOpposite v := by
      have hxproperty := x.property
      change (x.1 : Circle × ℝ) ∈ annularPunctureOpen v ∧
        (x.1 : Circle × ℝ) ∈ annularPunctureOpen (annularOpposite v) at hxproperty
      exact ⟨(mem_annularPunctureOpen_iff v x.1).mp hxproperty.1,
        (mem_annularPunctureOpen_iff (annularOpposite v) x.1).mp hxproperty.2⟩
    have hsource : (x.1 : Circle × ℝ).1 ∈ (stereographic' 1 v).source := by
      simpa [stereographic'_source] using hxpuncture.1
    have hcoord :
        (stereographic' 1 v (x.1 : Circle × ℝ).1) 0 ≠ 0 := by
      intro hzero
      apply hxpuncture.2
      apply (stereographic_eq_zero_iff v _ hsource).mp
      exact (euclideanFinOne_eq_zero_iff _).mpr hzero
    constructor
    · intro hnot
      refine ⟨hxpuncture.1, ?_⟩
      have hnpos : ¬0 < (stereographic' 1 v (x.1 : Circle × ℝ).1) 0 :=
        fun hpos => hnot ⟨hxpuncture.1, hpos⟩
      exact lt_of_le_of_ne (le_of_not_gt hnpos) hcoord
    · rintro ⟨_, hneg⟩ ⟨_, hpos⟩
      linarith
  rw [heq]
  exact (annularNegativeComponent v).2.preimage continuous_subtype_val

noncomputable def annularOverlapStepFunction (v : Circle)
    (x : annularDoublePunctureOpen v) : ℝ :=
  by
    classical
    exact if x ∈ annularOverlapPositiveSet v then 1 else 0

theorem annularOverlapStepFunction_isLocallyConstant (v : Circle) :
    IsLocallyConstant (annularOverlapStepFunction v) := by
  classical
  rw [IsLocallyConstant.iff_eventually_eq]
  intro x
  by_cases hx : x ∈ annularOverlapPositiveSet v
  · filter_upwards [(annularOverlapPositiveSet_isClopen v).2.mem_nhds hx] with y hy
    simp [annularOverlapStepFunction, hx, hy]
  · have hxc : x ∈ (annularOverlapPositiveSet v)ᶜ := hx
    filter_upwards [((annularOverlapPositiveSet_isClopen v).1.isOpen_compl.mem_nhds hxc)]
      with y hy
    have hynot : y ∉ annularOverlapPositiveSet v := hy
    simp [annularOverlapStepFunction, hx, hynot]

noncomputable def annularOverlapStepClosedForm (v : Circle) :
    DeRhamClosedForms (I := AnnularCylinderModel)
      (M := annularDoublePunctureOpen v) (A := ℝ) 0 :=
  ⟨smoothRealFunctionToZeroForm (I0 := AnnularCylinderModel)
      (smoothRealFunctionOfIsLocallyConstant AnnularCylinderModel
        (annularOverlapStepFunction v)
        (annularOverlapStepFunction_isLocallyConstant v)),
    deRhamDifferential_locallyConstant_zeroForm_eq_zero
      (I0 := AnnularCylinderModel) (annularOverlapStepFunction v)
      (annularOverlapStepFunction_isLocallyConstant v)⟩

noncomputable def annularOverlapStepClass (v : Circle) :
    DeRhamCohomology (I := AnnularCylinderModel)
      (M := annularDoublePunctureOpen v) (A := ℝ) 0 :=
  (DeRhamExactClosedForms (I := AnnularCylinderModel)
    (M := annularDoublePunctureOpen v) (A := ℝ) 0).mkQ
      (annularOverlapStepClosedForm v)

theorem annularOverlapStepClosedForm_restrict_positive (v : Circle) :
    deRhamClosedFormsRestrictionOfLE (I := AnnularCylinderModel) (A := ℝ)
        (annularPositiveComponent_le_doublePuncture v) 0
        (annularOverlapStepClosedForm v) =
      deRhamConstantZeroClosedForm (I0 := AnnularCylinderModel)
        (M0 := annularPositiveComponent v) 1 := by
  classical
  apply Subtype.ext
  apply DifferentialForm.ext
  intro x
  ext q
  rw [show q = (fun i : Fin 0 => nomatch i) from Subsingleton.elim _ _]
  simp only [deRhamClosedFormsRestrictionOfLE, restrictSmoothFormsOfLE,
    annularOverlapStepClosedForm,
    smoothRealFunctionToZeroForm, smoothRealFunctionOfIsLocallyConstant,
    deRhamConstantZeroClosedForm, smoothRealConstantFunction,
    ContinuousAlternatingMap.constOfIsEmpty_apply]
  have hx : TopologicalSpace.Opens.inclusion
      (annularPositiveComponent_le_doublePuncture v) x ∈
        annularOverlapPositiveSet v := x.property
  change
    (if TopologicalSpace.Opens.inclusion
        (annularPositiveComponent_le_doublePuncture v) x ∈
          annularOverlapPositiveSet v then 1 else 0) = 1
  simp [hx]

theorem annularOverlapStepClosedForm_restrict_negative (v : Circle) :
    deRhamClosedFormsRestrictionOfLE (I := AnnularCylinderModel) (A := ℝ)
        (annularNegativeComponent_le_doublePuncture v) 0
        (annularOverlapStepClosedForm v) =
      deRhamConstantZeroClosedForm (I0 := AnnularCylinderModel)
        (M0 := annularNegativeComponent v) 0 := by
  classical
  apply Subtype.ext
  apply DifferentialForm.ext
  intro x
  ext q
  rw [show q = (fun i : Fin 0 => nomatch i) from Subsingleton.elim _ _]
  simp only [deRhamClosedFormsRestrictionOfLE, restrictSmoothFormsOfLE,
    annularOverlapStepClosedForm,
    smoothRealFunctionToZeroForm, smoothRealFunctionOfIsLocallyConstant,
    deRhamConstantZeroClosedForm, smoothRealConstantFunction,
    ContinuousAlternatingMap.constOfIsEmpty_apply]
  have hx : TopologicalSpace.Opens.inclusion
      (annularNegativeComponent_le_doublePuncture v) x ∉
        annularOverlapPositiveSet v := by
    intro hxpos
    have hxPosAmbient : (x.1 : Circle × ℝ) ∈
        (annularPositiveComponent v : Set (Circle × ℝ)) := hxpos
    have hxNegAmbient : (x.1 : Circle × ℝ) ∈
        (annularNegativeComponent v : Set (Circle × ℝ)) := x.property
    have hmem : (x.1 : Circle × ℝ) ∈
        (annularPositiveComponent v ⊓ annularNegativeComponent v :
          TopologicalSpace.Opens (Circle × ℝ)) := ⟨hxPosAmbient, hxNegAmbient⟩
    rw [annularComponents_disjoint v] at hmem
    exact hmem
  change
    (if TopologicalSpace.Opens.inclusion
        (annularNegativeComponent_le_doublePuncture v) x ∈
          annularOverlapPositiveSet v then 1 else 0) = 0
  simp [hx]

theorem annularOverlapStepClass_restrict_positive (v : Circle) :
    deRhamCohomologyRestrictionOfLE (I := AnnularCylinderModel) (A := ℝ)
        (annularPositiveComponent_le_doublePuncture v) 0
        (annularOverlapStepClass v) =
      deRhamConstantH0Class (I0 := AnnularCylinderModel)
        (M0 := annularPositiveComponent v) 1 := by
  simp only [annularOverlapStepClass, deRhamCohomologyRestrictionOfLE,
    deRhamConstantH0Class]
  change
    (DeRhamExactClosedForms (I := AnnularCylinderModel)
      (M := annularPositiveComponent v) (A := ℝ) 0).mkQ
        (deRhamClosedFormsRestrictionOfLE (I := AnnularCylinderModel) (A := ℝ)
          (annularPositiveComponent_le_doublePuncture v) 0
          (annularOverlapStepClosedForm v)) = _
  rw [annularOverlapStepClosedForm_restrict_positive]

theorem annularOverlapStepClass_restrict_negative (v : Circle) :
    deRhamCohomologyRestrictionOfLE (I := AnnularCylinderModel) (A := ℝ)
        (annularNegativeComponent_le_doublePuncture v) 0
        (annularOverlapStepClass v) =
      deRhamConstantH0Class (I0 := AnnularCylinderModel)
        (M0 := annularNegativeComponent v) 0 := by
  simp only [annularOverlapStepClass, deRhamCohomologyRestrictionOfLE,
    deRhamConstantH0Class]
  change
    (DeRhamExactClosedForms (I := AnnularCylinderModel)
      (M := annularNegativeComponent v) (A := ℝ) 0).mkQ
        (deRhamClosedFormsRestrictionOfLE (I := AnnularCylinderModel) (A := ℝ)
          (annularNegativeComponent_le_doublePuncture v) 0
          (annularOverlapStepClosedForm v)) = _
  rw [annularOverlapStepClosedForm_restrict_negative]

theorem annularPositiveComponent_diffeomorph (v : Circle) :
    Nonempty
      (annularPositiveComponent v ≃ₘ⟮AnnularCylinderModel,
        𝓘(ℝ, EuclideanSpace ℝ (Fin 1) × ℝ)⟯ annularPositiveTarget) := by
  apply deRham_boundarylessExtendedChart_restriction_diffeomorph
    AnnularCylinderModel
    (e := annularPunctureChart v)
    (annularPunctureChart_mem_atlas v)
  · rfl
  · intro y hy
    change y ∈ ((annularPunctureChart v).extend AnnularCylinderModel).target
    rw [OpenPartialHomeomorph.extend_target]
    simp [annularPunctureChart, AnnularCylinderModel]
    exact Set.mem_univ y

theorem annularNegativeComponent_diffeomorph (v : Circle) :
    Nonempty
      (annularNegativeComponent v ≃ₘ⟮AnnularCylinderModel,
        𝓘(ℝ, EuclideanSpace ℝ (Fin 1) × ℝ)⟯ annularNegativeTarget) := by
  apply deRham_boundarylessExtendedChart_restriction_diffeomorph
    AnnularCylinderModel
    (e := annularPunctureChart v)
    (annularPunctureChart_mem_atlas v)
  · rfl
  · intro y hy
    change y ∈ ((annularPunctureChart v).extend AnnularCylinderModel).target
    rw [OpenPartialHomeomorph.extend_target]
    simp [annularPunctureChart, AnnularCylinderModel]
    exact Set.mem_univ y

theorem annularPositiveComponent_nonempty (v : Circle) :
    Nonempty (annularPositiveComponent v) := by
  rcases annularPositiveComponent_diffeomorph v with ⟨phi⟩
  exact ⟨phi.symm ⟨annularPositiveTarget_nonempty.choose,
    annularPositiveTarget_nonempty.choose_spec⟩⟩

theorem annularNegativeComponent_nonempty (v : Circle) :
    Nonempty (annularNegativeComponent v) := by
  rcases annularNegativeComponent_diffeomorph v with ⟨phi⟩
  exact ⟨phi.symm ⟨annularNegativeTarget_nonempty.choose,
    annularNegativeTarget_nonempty.choose_spec⟩⟩

theorem annularPuncture_H0_eq_constant (v : Circle)
    (alpha : DeRhamCohomology (I := AnnularCylinderModel)
      (M := annularPunctureOpen v) (A := ℝ) 0) :
    ∃ c : ℝ, alpha = deRhamConstantH0Class
      (I0 := AnnularCylinderModel) (M0 := annularPunctureOpen v) c := by
  rcases annularPuncture_diffeomorphic_convex v with
    ⟨V, hconvex, hne, ⟨phi⟩⟩
  exact deRhamH0_eq_constant_of_diffeomorphic_convex
    AnnularCylinderModel V hconvex ⟨hne.choose, hne.choose_spec⟩ phi alpha

theorem annularPositiveComponent_H0_eq_constant (v : Circle)
    (alpha : DeRhamCohomology (I := AnnularCylinderModel)
      (M := annularPositiveComponent v) (A := ℝ) 0) :
    ∃ c : ℝ, alpha = deRhamConstantH0Class
      (I0 := AnnularCylinderModel) (M0 := annularPositiveComponent v) c := by
  rcases annularPositiveComponent_diffeomorph v with ⟨phi⟩
  exact deRhamH0_eq_constant_of_diffeomorphic_convex
    AnnularCylinderModel annularPositiveTarget annularPositiveTarget_convex
    ⟨_, annularPositiveTarget_nonempty.choose_spec⟩ phi alpha

theorem annularNegativeComponent_H0_eq_constant (v : Circle)
    (alpha : DeRhamCohomology (I := AnnularCylinderModel)
      (M := annularNegativeComponent v) (A := ℝ) 0) :
    ∃ c : ℝ, alpha = deRhamConstantH0Class
      (I0 := AnnularCylinderModel) (M0 := annularNegativeComponent v) c := by
  rcases annularNegativeComponent_diffeomorph v with ⟨phi⟩
  exact deRhamH0_eq_constant_of_diffeomorphic_convex
    AnnularCylinderModel annularNegativeTarget annularNegativeTarget_convex
    ⟨_, annularNegativeTarget_nonempty.choose_spec⟩ phi alpha

set_option synthInstance.maxHeartbeats 100000 in
theorem annularDoublePuncture_H0_eq_constant_add_smul_step
    (v : Circle)
    (alpha : DeRhamCohomology (I := AnnularCylinderModel)
      (M := annularDoublePunctureOpen v) (A := ℝ) 0) :
    ∃ c d : ℝ,
      alpha =
        deRhamConstantH0Class (I0 := AnnularCylinderModel)
            (M0 := annularDoublePunctureOpen v) c +
          d • annularOverlapStepClass v := by
  classical
  induction alpha using Submodule.Quotient.induction_on with
  | _ omega =>
      let alphaPos :=
        deRhamCohomologyRestrictionOfLE (I := AnnularCylinderModel) (A := ℝ)
          (annularPositiveComponent_le_doublePuncture v) 0
          ((DeRhamExactClosedForms (I := AnnularCylinderModel)
            (M := annularDoublePunctureOpen v) (A := ℝ) 0).mkQ omega)
      let alphaNeg :=
        deRhamCohomologyRestrictionOfLE (I := AnnularCylinderModel) (A := ℝ)
          (annularNegativeComponent_le_doublePuncture v) 0
          ((DeRhamExactClosedForms (I := AnnularCylinderModel)
            (M := annularDoublePunctureOpen v) (A := ℝ) 0).mkQ omega)
      rcases annularPositiveComponent_H0_eq_constant v alphaPos with ⟨cPos, hcPos⟩
      rcases annularNegativeComponent_H0_eq_constant v alphaNeg with ⟨cNeg, hcNeg⟩
      refine ⟨cNeg, cPos - cNeg, ?_⟩
      have hcPos' :
          (DeRhamExactClosedForms (I := AnnularCylinderModel)
            (M := annularPositiveComponent v) (A := ℝ) 0).mkQ
              (deRhamClosedFormsRestrictionOfLE
                (I := AnnularCylinderModel) (A := ℝ)
                (annularPositiveComponent_le_doublePuncture v) 0 omega) =
            (DeRhamExactClosedForms (I := AnnularCylinderModel)
              (M := annularPositiveComponent v) (A := ℝ) 0).mkQ
                (deRhamConstantZeroClosedForm (I0 := AnnularCylinderModel)
                  (M0 := annularPositiveComponent v) cPos) := by
        simpa [alphaPos, deRhamCohomologyRestrictionOfLE,
          deRhamConstantH0Class] using hcPos
      have hcNeg' :
          (DeRhamExactClosedForms (I := AnnularCylinderModel)
            (M := annularNegativeComponent v) (A := ℝ) 0).mkQ
              (deRhamClosedFormsRestrictionOfLE
                (I := AnnularCylinderModel) (A := ℝ)
                (annularNegativeComponent_le_doublePuncture v) 0 omega) =
            (DeRhamExactClosedForms (I := AnnularCylinderModel)
              (M := annularNegativeComponent v) (A := ℝ) 0).mkQ
                (deRhamConstantZeroClosedForm (I0 := AnnularCylinderModel)
                  (M0 := annularNegativeComponent v) cNeg) := by
        simpa [alphaNeg, deRhamCohomologyRestrictionOfLE,
          deRhamConstantH0Class] using hcNeg
      have hcPosClosed :=
        (deRhamH0_mkQ_eq_iff AnnularCylinderModel _ _).mp hcPos'
      have hcNegClosed :=
        (deRhamH0_mkQ_eq_iff AnnularCylinderModel _ _).mp hcNeg'
      have hforms :
          omega =
            deRhamConstantZeroClosedForm (I0 := AnnularCylinderModel)
                (M0 := annularDoublePunctureOpen v) cNeg +
              (cPos - cNeg) • annularOverlapStepClosedForm v := by
        apply Subtype.ext
        apply DifferentialForm.ext
        intro x
        ext q
        rw [show q = (fun i : Fin 0 => nomatch i) from Subsingleton.elim _ _]
        have hxcover : (x.1 : Circle × ℝ) ∈
            (annularPositiveComponent v : Set (Circle × ℝ)) ∨
          (x.1 : Circle × ℝ) ∈
            (annularNegativeComponent v : Set (Circle × ℝ)) := by
          have hx : (x.1 : Circle × ℝ) ∈
              (annularPositiveComponent v ⊔ annularNegativeComponent v :
                TopologicalSpace.Opens (Circle × ℝ)) := by
            rw [annularComponents_cover_doublePuncture v]
            exact x.property
          exact hx
        rcases hxcover with hxPos | hxNeg
        · let xPos : annularPositiveComponent v := ⟨x.1, hxPos⟩
          have hvalue := congrArg
            (fun eta : DeRhamClosedForms (I := AnnularCylinderModel)
                (M := annularPositiveComponent v) (A := ℝ) 0 =>
              eta.1.toFun xPos (fun i : Fin 0 => nomatch i)) hcPosClosed
          have harg :
              (mfderiv AnnularCylinderModel AnnularCylinderModel
                  (TopologicalSpace.Opens.inclusion
                    (annularPositiveComponent_le_doublePuncture v)) xPos ∘
                (fun i : Fin 0 => nomatch i)) =
              (fun i : Fin 0 => nomatch i) := Subsingleton.elim _ _
          have hvalue' :
              omega.1.toFun x (fun i : Fin 0 => nomatch i) = cPos := by
            simpa [xPos, deRhamClosedFormsRestrictionOfLE,
              restrictSmoothFormsOfLE, restrictSmoothFormOfLE,
              deRhamConstantZeroClosedForm, smoothRealFunctionToZeroForm,
              smoothRealConstantFunction, harg] using hvalue
          have hxStep : x ∈ annularOverlapPositiveSet v := hxPos
          simp only [deRhamConstantZeroClosedForm, annularOverlapStepClosedForm,
            smoothRealFunctionToZeroForm, smoothRealConstantFunction,
            smoothRealFunctionOfIsLocallyConstant]
          change omega.1.toFun x (fun i : Fin 0 => nomatch i) =
            cNeg + (cPos - cNeg) *
              (if x ∈ annularOverlapPositiveSet v then 1 else 0)
          rw [if_pos hxStep, hvalue']
          ring
        · let xNeg : annularNegativeComponent v := ⟨x.1, hxNeg⟩
          have hvalue := congrArg
            (fun eta : DeRhamClosedForms (I := AnnularCylinderModel)
                (M := annularNegativeComponent v) (A := ℝ) 0 =>
              eta.1.toFun xNeg (fun i : Fin 0 => nomatch i)) hcNegClosed
          have harg :
              (mfderiv AnnularCylinderModel AnnularCylinderModel
                  (TopologicalSpace.Opens.inclusion
                    (annularNegativeComponent_le_doublePuncture v)) xNeg ∘
                (fun i : Fin 0 => nomatch i)) =
              (fun i : Fin 0 => nomatch i) := Subsingleton.elim _ _
          have hvalue' :
              omega.1.toFun x (fun i : Fin 0 => nomatch i) = cNeg := by
            simpa [xNeg, deRhamClosedFormsRestrictionOfLE,
              restrictSmoothFormsOfLE, restrictSmoothFormOfLE,
              deRhamConstantZeroClosedForm, smoothRealFunctionToZeroForm,
              smoothRealConstantFunction, harg] using hvalue
          have hxStep : x ∉ annularOverlapPositiveSet v := by
            intro hxPos
            have hmem : (x.1 : Circle × ℝ) ∈
                (annularPositiveComponent v ⊓ annularNegativeComponent v :
                  TopologicalSpace.Opens (Circle × ℝ)) := ⟨hxPos, hxNeg⟩
            rw [annularComponents_disjoint v] at hmem
            exact hmem
          simp only [deRhamConstantZeroClosedForm, annularOverlapStepClosedForm,
            smoothRealFunctionToZeroForm, smoothRealConstantFunction,
            smoothRealFunctionOfIsLocallyConstant]
          change omega.1.toFun x (fun i : Fin 0 => nomatch i) =
            cNeg + (cPos - cNeg) *
              (if x ∈ annularOverlapPositiveSet v then 1 else 0)
          rw [if_neg hxStep, hvalue']
          ring
      have hquot := congrArg
        (DeRhamExactClosedForms (I := AnnularCylinderModel)
          (M := annularDoublePunctureOpen v) (A := ℝ) 0).mkQ hforms
      simpa only [deRhamConstantH0Class, annularOverlapStepClass,
        map_add, map_smul] using hquot

theorem annularPunctures_cover (v : Circle) :
    annularPunctureOpen v ⊔ annularPunctureOpen (annularOpposite v) = ⊤ := by
  ext p
  constructor
  · intro
    trivial
  · intro
    change p ∈ annularPunctureOpen v ∨
      p ∈ annularPunctureOpen (annularOpposite v)
    by_cases hp : p.1 = v
    · right
      apply (mem_annularPunctureOpen_iff (annularOpposite v) p).mpr
      rw [hp]
      exact (annularOpposite_ne v).symm
    · left
      exact (mem_annularPunctureOpen_iff v p).mpr hp

noncomputable def annularStepConnectingClass (v : Circle) :
    DeRhamCohomology (I := AnnularCylinderModel)
      (M := Circle × ℝ) (A := ℝ) 1 :=
  deRhamMayerVietorisConnectingOfPartitionOfUnity (A := ℝ)
    AnnularCylinderModel (annularPunctureOpen v)
      (annularPunctureOpen (annularOpposite v)) (annularPunctures_cover v) 0
      (annularOverlapStepClass v)

set_option synthInstance.maxHeartbeats 100000 in
set_option maxHeartbeats 800000 in
theorem annularCylinder_deRhamH1_eq_smul_stepConnecting
    (v : Circle)
    (alpha : DeRhamCohomology (I := AnnularCylinderModel)
      (M := Circle × ℝ) (A := ℝ) 1) :
    ∃ d : ℝ, alpha = d • annularStepConnectingClass v := by
  let U := annularPunctureOpen v
  let V := annularPunctureOpen (annularOpposite v)
  let hcover : U ⊔ V = ⊤ := annularPunctures_cover v
  letI : Subsingleton
      (DeRhamCohomology (I := AnnularCylinderModel) (M := U) (A := ℝ) 1) := by
    simpa [U] using annularPuncture_deRhamH1_subsingleton v
  letI : Subsingleton
      (DeRhamCohomology (I := AnnularCylinderModel) (M := V) (A := ℝ) 1) := by
    simpa [V] using annularPuncture_deRhamH1_subsingleton (annularOpposite v)
  let connecting :=
    deRhamMayerVietorisConnectingOfPartitionOfUnity (A := ℝ)
      AnnularCylinderModel U V hcover 0
  have hrestriction :
      deRhamMayerVietorisRestriction (I := AnnularCylinderModel) (A := ℝ)
          U V 1 alpha = 0 := by
    apply Prod.ext
    · exact Subsingleton.elim _ _
    · exact Subsingleton.elim _ _
  have hexact :=
    deRham_mayerVietoris_exact_connecting_restriction_of_partitionOfUnity
      (A := ℝ) AnnularCylinderModel U V hcover 0
  have hrange : alpha ∈ Set.range connecting := (hexact alpha).mp hrestriction
  rcases hrange with ⟨eta, heta⟩
  change DeRhamCohomology (I := AnnularCylinderModel)
    (M := annularDoublePunctureOpen v) (A := ℝ) 0 at eta
  rcases annularDoublePuncture_H0_eq_constant_add_smul_step v eta with
    ⟨c, d, hdecomp⟩
  have hconstant_range :
      deRhamConstantH0Class (I0 := AnnularCylinderModel)
          (M0 := annularDoublePunctureOpen v) c ∈
        Set.range
          (deRhamMayerVietorisDifference (I := AnnularCylinderModel) (A := ℝ)
            U V 0) := by
    refine ⟨
      (deRhamConstantH0Class (I0 := AnnularCylinderModel) (M0 := U) c,
        0), ?_⟩
    change
      deRhamCohomologyRestrictionOfLE (I := AnnularCylinderModel) (A := ℝ)
          (W := annularDoublePunctureOpen v) (V := U) inf_le_left 0
          (deRhamConstantH0Class (I0 := AnnularCylinderModel) (M0 := U) c) -
        deRhamCohomologyRestrictionOfLE (I := AnnularCylinderModel) (A := ℝ)
          (W := annularDoublePunctureOpen v) (V := V) inf_le_right 0 0 =
        deRhamConstantH0Class (I0 := AnnularCylinderModel)
          (M0 := annularDoublePunctureOpen v) c
    rw [deRhamCohomologyRestrictionOfLE_constant]
    simp
  have hconstant_zero :
      connecting
          (deRhamConstantH0Class (I0 := AnnularCylinderModel)
            (M0 := annularDoublePunctureOpen v) c) = 0 := by
    have hexact0 :=
      deRham_mayerVietoris_exact_difference_connecting_of_partitionOfUnity
        (A := ℝ) AnnularCylinderModel U V hcover 0
    exact (hexact0 _).mpr hconstant_range
  refine ⟨d, ?_⟩
  calc
    alpha = connecting eta := heta.symm
    _ = connecting
        (deRhamConstantH0Class (I0 := AnnularCylinderModel)
            (M0 := annularDoublePunctureOpen v) c +
          d • annularOverlapStepClass v) := congrArg connecting hdecomp
    _ = connecting
          (deRhamConstantH0Class (I0 := AnnularCylinderModel)
            (M0 := annularDoublePunctureOpen v) c) +
        connecting (d • annularOverlapStepClass v) :=
      deRhamMayerVietorisConnectingOfPartitionOfUnity_add
        AnnularCylinderModel U V hcover 0 _ _
    _ = 0 + d • connecting (annularOverlapStepClass v) := by
      have hsmul :=
        deRhamMayerVietorisConnectingOfPartitionOfUnity_smul
          AnnularCylinderModel U V hcover 0 d (annularOverlapStepClass v)
      change connecting (d • annularOverlapStepClass v) =
        d • connecting (annularOverlapStepClass v) at hsmul
      rw [hconstant_zero, hsmul]
    _ = d • annularStepConnectingClass v := by
      simp [annularStepConnectingClass, U, V, connecting]

set_option synthInstance.maxHeartbeats 100000 in
set_option maxHeartbeats 800000 in
theorem annularStepConnectingClass_ne_zero (v : Circle) :
    annularStepConnectingClass v ≠ 0 := by
  intro hzero
  let U := annularPunctureOpen v
  let V := annularPunctureOpen (annularOpposite v)
  let hcover : U ⊔ V = ⊤ := annularPunctures_cover v
  let connecting :=
    deRhamMayerVietorisConnectingOfPartitionOfUnity (A := ℝ)
      AnnularCylinderModel U V hcover 0
  have hzero' : connecting (annularOverlapStepClass v) = 0 := by
    simpa [annularStepConnectingClass, U, V, connecting] using hzero
  have hexact :=
    deRham_mayerVietoris_exact_difference_connecting_of_partitionOfUnity
      (A := ℝ) AnnularCylinderModel U V hcover 0
  have hrange : annularOverlapStepClass v ∈
      Set.range
        (deRhamMayerVietorisDifference (I := AnnularCylinderModel) (A := ℝ)
          U V 0) := (hexact _).mp hzero'
  rcases hrange with ⟨⟨alpha, beta⟩, hab⟩
  rcases annularPuncture_H0_eq_constant v alpha with ⟨c, hc⟩
  rcases annularPuncture_H0_eq_constant (annularOpposite v) beta with ⟨d, hd⟩
  rw [hc, hd] at hab
  change
    deRhamCohomologyRestrictionOfLE (I := AnnularCylinderModel) (A := ℝ)
        (W := annularDoublePunctureOpen v) (V := U) inf_le_left 0
        (deRhamConstantH0Class (I0 := AnnularCylinderModel) (M0 := U) c) -
      deRhamCohomologyRestrictionOfLE (I := AnnularCylinderModel) (A := ℝ)
        (W := annularDoublePunctureOpen v) (V := V) inf_le_right 0
        (deRhamConstantH0Class (I0 := AnnularCylinderModel) (M0 := V) d) =
      annularOverlapStepClass v at hab
  rw [deRhamCohomologyRestrictionOfLE_constant,
    deRhamCohomologyRestrictionOfLE_constant,
    deRhamConstantH0Class_sub] at hab
  have hpositive := congrArg
    (deRhamCohomologyRestrictionOfLE (I := AnnularCylinderModel) (A := ℝ)
      (annularPositiveComponent_le_doublePuncture v) 0) hab
  have hnegative := congrArg
    (deRhamCohomologyRestrictionOfLE (I := AnnularCylinderModel) (A := ℝ)
      (annularNegativeComponent_le_doublePuncture v) 0) hab
  rw [deRhamCohomologyRestrictionOfLE_constant,
    annularOverlapStepClass_restrict_positive] at hpositive
  rw [deRhamCohomologyRestrictionOfLE_constant,
    annularOverlapStepClass_restrict_negative] at hnegative
  letI : Nonempty (annularPositiveComponent v) :=
    annularPositiveComponent_nonempty v
  letI : Nonempty (annularNegativeComponent v) :=
    annularNegativeComponent_nonempty v
  have hcd_one : c - d = 1 :=
    deRhamConstantH0Class_injective hpositive
  have hcd_zero : c - d = 0 :=
    deRhamConstantH0Class_injective hnegative
  linarith

set_option synthInstance.maxHeartbeats 100000 in
set_option maxHeartbeats 800000 in
theorem annularCylinder_deRhamH1_eq_smul_of_ne_zero
    (v : Circle)
    (tau : DeRhamCohomology (I := AnnularCylinderModel)
      (M := Circle × ℝ) (A := ℝ) 1)
    (htau : tau ≠ 0)
    (alpha : DeRhamCohomology (I := AnnularCylinderModel)
      (M := Circle × ℝ) (A := ℝ) 1) :
    ∃ c : ℝ, alpha = c • tau := by
  rcases annularCylinder_deRhamH1_eq_smul_stepConnecting v tau with
    ⟨d, hd⟩
  have hd_ne : d ≠ 0 := by
    intro hd_zero
    apply htau
    simpa [hd_zero] using hd
  rcases annularCylinder_deRhamH1_eq_smul_stepConnecting v alpha with
    ⟨e, he⟩
  refine ⟨e / d, ?_⟩
  rw [he, hd]
  rw [smul_smul]
  field_simp

/-- First de Rham cohomology of any smooth annulus is generated by each of
its nonzero classes. -/
theorem deRhamH1_eq_smul_of_diffeomorphic_annularCylinder
    {E H M : Type*}
    [NormedAddCommGroup E] [NormedSpace ℝ E]
    [TopologicalSpace H] [TopologicalSpace M] [ChartedSpace H M]
    (I : ModelWithCorners ℝ E H) [IsManifold I ∞ M]
    (phi : M ≃ₘ⟮I, AnnularCylinderModel⟯ Circle × ℝ)
    (v : Circle)
    (tau : DeRhamCohomology (I := I) (M := M) (A := ℝ) 1)
    (htau : tau ≠ 0)
    (alpha : DeRhamCohomology (I := I) (M := M) (A := ℝ) 1) :
    ∃ c : ℝ, alpha = c • tau := by
  let tauCylinder := deRhamCohomologyPullbackDiffeomorph
    AnnularCylinderModel I phi.symm 1 tau
  have htauCylinder : tauCylinder ≠ 0 := by
    intro htauCylinder_zero
    apply htau
    calc
      tau = deRhamCohomologyPullbackDiffeomorph
          I AnnularCylinderModel phi 1 tauCylinder :=
        (deRhamCohomologyPullbackDiffeomorph_comp_symm
          I AnnularCylinderModel phi 1 tau).symm
      _ = 0 := by
        rw [htauCylinder_zero]
        exact (deRhamCohomologyPullbackDiffeomorph
          I AnnularCylinderModel phi 1).map_zero
  let alphaCylinder := deRhamCohomologyPullbackDiffeomorph
    AnnularCylinderModel I phi.symm 1 alpha
  rcases annularCylinder_deRhamH1_eq_smul_of_ne_zero
      v tauCylinder htauCylinder alphaCylinder with ⟨c, hc⟩
  refine ⟨c, ?_⟩
  calc
    alpha = deRhamCohomologyPullbackDiffeomorph
        I AnnularCylinderModel phi 1 alphaCylinder :=
      (deRhamCohomologyPullbackDiffeomorph_comp_symm
        I AnnularCylinderModel phi 1 alpha).symm
    _ = deRhamCohomologyPullbackDiffeomorph
        I AnnularCylinderModel phi 1 (c • tauCylinder) := congrArg _ hc
    _ = c • deRhamCohomologyPullbackDiffeomorph
        I AnnularCylinderModel phi 1 tauCylinder := by rw [map_smul]
    _ = c • tau := by
      rw [deRhamCohomologyPullbackDiffeomorph_comp_symm]

set_option synthInstance.maxHeartbeats 100000 in
set_option maxHeartbeats 800000 in
/-- Two closed one-forms on a smooth annulus represent the same de Rham
class if they have the same period on a cycle on which the second period is
nonzero. -/
theorem deRhamH1_class_eq_of_annular_eq_period
    {E H M : Type*}
    [NormedAddCommGroup E] [NormedSpace ℝ E]
    [TopologicalSpace H] [TopologicalSpace M] [ChartedSpace H M]
    (I : ModelWithCorners ℝ E H) [IsManifold I ∞ M]
    (phi : M ≃ₘ⟮I, AnnularCylinderModel⟯ Circle × ℝ)
    (v : Circle)
    (alpha tau : DeRhamClosedForms (I := I) (M := M) (A := ℝ) 1)
    (c : SingularChain (I := I) (M := M) 1 ∞)
    (hcycle : boundary (I := I) c = 0)
    (hperiod :
      integrateSmoothChain (I := I)
          (alpha : SmoothForms (I := I) (M := M) ℝ 1) c =
        integrateSmoothChain (I := I)
          (tau : SmoothForms (I := I) (M := M) ℝ 1) c)
    (htauPeriod :
      integrateSmoothChain (I := I)
        (tau : SmoothForms (I := I) (M := M) ℝ 1) c ≠ 0) :
    (DeRhamExactClosedForms (I := I) (M := M) (A := ℝ) 1).mkQ alpha =
      (DeRhamExactClosedForms (I := I) (M := M) (A := ℝ) 1).mkQ tau := by
  let alphaClass :=
    (DeRhamExactClosedForms (I := I) (M := M) (A := ℝ) 1).mkQ alpha
  let tauClass :=
    (DeRhamExactClosedForms (I := I) (M := M) (A := ℝ) 1).mkQ tau
  have htauClass : tauClass ≠ 0 :=
    deRhamCohomologyClass_ne_zero_of_nonzero_period
      (I := I) tau c hcycle htauPeriod
  rcases deRhamH1_eq_smul_of_diffeomorphic_annularCylinder
      I phi v tauClass htauClass alphaClass with ⟨a, ha⟩
  have hdiffClass :
      (DeRhamExactClosedForms (I := I) (M := M) (A := ℝ) 1).mkQ
          (alpha - a • tau) = 0 := by
    rw [map_sub, map_smul]
    change alphaClass - a • tauClass = 0
    rw [ha, sub_self]
  have hmem :
      (alpha - a • tau : DeRhamClosedForms
        (I := I) (M := M) (A := ℝ) 1) ∈
        DeRhamExactClosedForms (I := I) (M := M) (A := ℝ) 1 := by
    rw [← Submodule.Quotient.mk_eq_zero]
    simpa [Submodule.mkQ_apply] using hdiffClass
  have hexact :
      ((alpha - a • tau : DeRhamClosedForms
          (I := I) (M := M) (A := ℝ) 1) :
        SmoothForms (I := I) (M := M) ℝ 1) ∈
        DeRhamExactForms (I := I) (M := M) (A := ℝ) 1 := by
    simpa [DeRhamExactClosedForms] using hmem
  have hzero := integrateSmoothChain_eq_zero_of_mem_deRhamExactForms_one
    (I := I)
    (omega := ((alpha - a • tau : DeRhamClosedForms
      (I := I) (M := M) (A := ℝ) 1) :
        SmoothForms (I := I) (M := M) ℝ 1)) hexact c hcycle
  change integrateSmoothChain (I := I)
    ((alpha : SmoothForms (I := I) (M := M) ℝ 1) -
      a • (tau : SmoothForms (I := I) (M := M) ℝ 1)) c = 0 at hzero
  rw [show
      (alpha : SmoothForms (I := I) (M := M) ℝ 1) -
          a • (tau : SmoothForms (I := I) (M := M) ℝ 1) =
        (alpha : SmoothForms (I := I) (M := M) ℝ 1) +
          (-a) • (tau : SmoothForms (I := I) (M := M) ℝ 1) by module,
    integrateSmoothChain_add_form, integrateSmoothChain_smul_form] at hzero
  have ha_one : a = 1 := by
    rw [hperiod] at hzero
    have hfactor :
        (1 - a) * integrateSmoothChain (I := I)
          (tau : SmoothForms (I := I) (M := M) ℝ 1) c = 0 := by
      calc
        _ = integrateSmoothChain (I := I)
              (tau : SmoothForms (I := I) (M := M) ℝ 1) c +
            -a * integrateSmoothChain (I := I)
              (tau : SmoothForms (I := I) (M := M) ℝ 1) c := by ring
        _ = 0 := hzero
    have hone : 1 - a = 0 :=
      (mul_eq_zero.mp hfactor).resolve_right htauPeriod
    linarith
  change alphaClass = tauClass
  rw [ha, ha_one, one_smul]

set_option synthInstance.maxHeartbeats 100000 in
set_option maxHeartbeats 800000 in
/-- On a smooth annulus, closed one-forms whose periods agree up to sign
represent de Rham classes which agree up to the same sign. -/
theorem deRhamH1_class_eq_or_neg_of_annular_period_eq_or_neg
    {E H M : Type*}
    [NormedAddCommGroup E] [NormedSpace ℝ E]
    [TopologicalSpace H] [TopologicalSpace M] [ChartedSpace H M]
    (I : ModelWithCorners ℝ E H) [IsManifold I ∞ M]
    (phi : M ≃ₘ⟮I, AnnularCylinderModel⟯ Circle × ℝ)
    (v : Circle)
    (alpha tau : DeRhamClosedForms (I := I) (M := M) (A := ℝ) 1)
    (c : SingularChain (I := I) (M := M) 1 ∞)
    (hcycle : boundary (I := I) c = 0)
    (hperiod :
      integrateSmoothChain (I := I)
          (alpha : SmoothForms (I := I) (M := M) ℝ 1) c =
          integrateSmoothChain (I := I)
            (tau : SmoothForms (I := I) (M := M) ℝ 1) c ∨
      integrateSmoothChain (I := I)
          (alpha : SmoothForms (I := I) (M := M) ℝ 1) c =
          -integrateSmoothChain (I := I)
            (tau : SmoothForms (I := I) (M := M) ℝ 1) c)
    (htauPeriod :
      integrateSmoothChain (I := I)
        (tau : SmoothForms (I := I) (M := M) ℝ 1) c ≠ 0) :
    (DeRhamExactClosedForms (I := I) (M := M) (A := ℝ) 1).mkQ alpha =
        (DeRhamExactClosedForms (I := I) (M := M) (A := ℝ) 1).mkQ tau ∨
      (DeRhamExactClosedForms (I := I) (M := M) (A := ℝ) 1).mkQ alpha =
        -(DeRhamExactClosedForms (I := I) (M := M) (A := ℝ) 1).mkQ tau := by
  rcases hperiod with hperiod | hperiod
  · exact Or.inl (deRhamH1_class_eq_of_annular_eq_period
      I phi v alpha tau c hcycle hperiod htauPeriod)
  · right
    have hnegPeriod :
        integrateSmoothChain (I := I)
            (alpha : SmoothForms (I := I) (M := M) ℝ 1) c =
          integrateSmoothChain (I := I)
            ((-tau : DeRhamClosedForms
              (I := I) (M := M) (A := ℝ) 1) :
                SmoothForms (I := I) (M := M) ℝ 1) c := by
      rw [show
          ((-tau : DeRhamClosedForms
              (I := I) (M := M) (A := ℝ) 1) :
                SmoothForms (I := I) (M := M) ℝ 1) =
            (-1 : ℝ) •
              (tau : SmoothForms (I := I) (M := M) ℝ 1) by
                change -tau.1 = (-1 : ℝ) • tau.1
                module,
        integrateSmoothChain_smul_form]
      simpa using hperiod
    have hnegPeriod_ne :
        integrateSmoothChain (I := I)
          ((-tau : DeRhamClosedForms
            (I := I) (M := M) (A := ℝ) 1) :
              SmoothForms (I := I) (M := M) ℝ 1) c ≠ 0 := by
      rw [show
          ((-tau : DeRhamClosedForms
              (I := I) (M := M) (A := ℝ) 1) :
                SmoothForms (I := I) (M := M) ℝ 1) =
            (-1 : ℝ) •
              (tau : SmoothForms (I := I) (M := M) ℝ 1) by
                change -tau.1 = (-1 : ℝ) • tau.1
                module,
        integrateSmoothChain_smul_form]
      simpa using htauPeriod
    have hclass := deRhamH1_class_eq_of_annular_eq_period
      I phi v alpha (-tau) c hcycle hnegPeriod hnegPeriod_ne
    simpa using hclass

/-- A linear map onto the first de Rham cohomology of a smooth annulus is
surjective as soon as its range contains one nonzero class. -/
theorem deRhamH1_map_surjective_of_annular_nonzero_mem_range
    {E₁ H₁ M₁ E₂ H₂ M₂ : Type*}
    [NormedAddCommGroup E₁] [NormedSpace ℝ E₁]
    [NormedAddCommGroup E₂] [NormedSpace ℝ E₂]
    [TopologicalSpace H₁] [TopologicalSpace M₁] [ChartedSpace H₁ M₁]
    [TopologicalSpace H₂] [TopologicalSpace M₂] [ChartedSpace H₂ M₂]
    (I₁ : ModelWithCorners ℝ E₁ H₁) (I₂ : ModelWithCorners ℝ E₂ H₂)
    [IsManifold I₁ ∞ M₁] [IsManifold I₂ ∞ M₂]
    (phi : M₂ ≃ₘ⟮I₂, AnnularCylinderModel⟯ Circle × ℝ)
    (v : Circle)
    (f : DeRhamCohomology (I := I₁) (M := M₁) (A := ℝ) 1 →ₗ[ℝ]
      DeRhamCohomology (I := I₂) (M := M₂) (A := ℝ) 1)
    (tau : DeRhamCohomology (I := I₂) (M := M₂) (A := ℝ) 1)
    (htau : tau ≠ 0) (htau_range : tau ∈ LinearMap.range f) :
    Function.Surjective f := by
  intro alpha
  rcases deRhamH1_eq_smul_of_diffeomorphic_annularCylinder
      I₂ phi v tau htau alpha with ⟨c, hc⟩
  rcases htau_range with ⟨beta, hbeta⟩
  refine ⟨c • beta, ?_⟩
  rw [map_smul, hbeta, ← hc]

/-- For an annular inclusion, one closed form with a nonzero period after
restriction already makes the restriction map on first de Rham cohomology
surjective. -/
theorem deRhamCohomologyRestrictionOfLE_surjective_of_annular_nonzero_period
    {E H M : Type*}
    [NormedAddCommGroup E] [NormedSpace ℝ E]
    [TopologicalSpace H] [TopologicalSpace M] [ChartedSpace H M]
    (I : ModelWithCorners ℝ E H) [IsManifold I ∞ M]
    {W V : TopologicalSpace.Opens M} (hWV : W ≤ V)
    (phi : W ≃ₘ⟮I, AnnularCylinderModel⟯ Circle × ℝ)
    (v : Circle)
    (omega : DeRhamClosedForms (I := I) (M := V) (A := ℝ) 1)
    (c : SingularChain (I := I) (M := W) 1 ∞)
    (hcycle : boundary (I := I) c = 0)
    (hperiod :
      integrateSmoothChain (I := I)
        (restrictSmoothFormsOfLE (I := I) (A := ℝ) hWV 1
          (omega : SmoothForms (I := I) (M := V) ℝ 1)) c ≠ 0) :
    Function.Surjective
      (deRhamCohomologyRestrictionOfLE (I := I) (A := ℝ) hWV 1) := by
  let beta :=
    (DeRhamExactClosedForms (I := I) (M := V) (A := ℝ) 1).mkQ omega
  let tau := deRhamCohomologyRestrictionOfLE
    (I := I) (A := ℝ) hWV 1 beta
  have htau : tau ≠ 0 := by
    exact deRhamCohomologyRestrictionOfLE_ne_zero_of_nonzero_period
      (I := I) hWV omega c hcycle hperiod
  apply deRhamH1_map_surjective_of_annular_nonzero_mem_range
    I I phi v
    (deRhamCohomologyRestrictionOfLE (I := I) (A := ℝ) hWV 1)
    tau htau
  exact ⟨beta, rfl⟩

set_option synthInstance.maxHeartbeats 100000 in
set_option maxHeartbeats 800000 in
/-- In a two-open cover, restriction from the left member to the
intersection is injective in degree one when both the ambient space and the
right member have trivial first de Rham cohomology. -/
theorem deRhamH1_left_restriction_injective_of_ambient_right_subsingleton
    {E H M : Type*}
    [NormedAddCommGroup E] [NormedSpace ℝ E] [FiniteDimensional ℝ E]
    [TopologicalSpace H] [TopologicalSpace M] [ChartedSpace H M]
    (I : ModelWithCorners ℝ E H) [IsManifold I ∞ M]
    [T2Space M] [SigmaCompactSpace M]
    [Subsingleton
      (DeRhamCohomology (I := I) (M := M) (A := ℝ) 1)]
    (U V : TopologicalSpace.Opens M) (hcover : U ⊔ V = ⊤)
    [Subsingleton
      (DeRhamCohomology (I := I) (M := V) (A := ℝ) 1)] :
    Function.Injective
      (deRhamCohomologyRestrictionOfLE (I := I) (A := ℝ)
        (W := (U ⊓ V : TopologicalSpace.Opens M)) (V := U)
        inf_le_left 1) := by
  intro alpha beta hab
  let rho := deRhamCohomologyRestrictionOfLE
    (I := I) (A := ℝ)
    (W := (U ⊓ V : TopologicalSpace.Opens M)) (V := U)
    inf_le_left 1
  let sigma := deRhamCohomologyRestrictionOfLE
    (I := I) (A := ℝ)
    (W := (U ⊓ V : TopologicalSpace.Opens M)) (V := V)
    inf_le_right 1
  let delta := alpha - beta
  have hrho_delta : rho delta = 0 := by
    change (deRhamCohomologyRestrictionOfLE (I := I) (A := ℝ)
      (W := (U ⊓ V : TopologicalSpace.Opens M)) (V := U)
      inf_le_left 1) (alpha - beta) = 0
    rw [(deRhamCohomologyRestrictionOfLE (I := I) (A := ℝ)
      (W := (U ⊓ V : TopologicalSpace.Opens M)) (V := U)
      inf_le_left 1).map_sub, hab, sub_self]
  let zeroV : DeRhamCohomology (I := I) (M := V) (A := ℝ) 1 := 0
  have hdiff :
      deRhamMayerVietorisDifference (I := I) (A := ℝ) U V 1
          (delta, zeroV) = 0 := by
    change rho delta - sigma zeroV = 0
    rw [hrho_delta]
    have hsigma_zero : sigma zeroV = 0 := by
      exact sigma.map_zero
    rw [hsigma_zero, sub_zero]
  rcases deRham_mayerVietoris_longExact (A := ℝ) I U V hcover with ⟨LES⟩
  rcases (LES.exact_restriction_difference 1 (delta, zeroV)).mp hdiff with
    ⟨ambient, hambient⟩
  have hambient_zero : ambient = 0 := Subsingleton.elim _ _
  have hpair : (delta, zeroV) =
      (0 : DeRhamCohomology (I := I) (M := U) (A := ℝ) 1 ×
        DeRhamCohomology (I := I) (M := V) (A := ℝ) 1) := by
    calc
      (delta, zeroV) = deRhamMayerVietorisRestriction
          (I := I) (A := ℝ) U V 1 ambient := hambient.symm
      _ = deRhamMayerVietorisRestriction
          (I := I) (A := ℝ) U V 1 0 := congrArg _ hambient_zero
      _ = 0 := by
        apply Prod.ext
        · exact (deRhamCohomologyRestrictionToOpen
            (I := I) (M := M) (A := ℝ) U 1).map_zero
        · exact (deRhamCohomologyRestrictionToOpen
            (I := I) (M := M) (A := ℝ) V 1).map_zero
  have hdelta : delta = 0 := congrArg Prod.fst hpair
  exact sub_eq_zero.mp hdelta


set_option synthInstance.maxHeartbeats 100000 in
/-- In a two-open cover with annular overlap and trivial ambient first
cohomology, nontrivial first cohomology on the left forces vanishing first
cohomology on the right. -/
theorem deRhamH1_subsingleton_of_mayerVietoris_annular_and_left_nontrivial
    {E H M : Type*}
    [NormedAddCommGroup E] [NormedSpace ℝ E] [FiniteDimensional ℝ E]
    [TopologicalSpace H] [TopologicalSpace M] [ChartedSpace H M]
    (I : ModelWithCorners ℝ E H) [IsManifold I ∞ M]
    [T2Space M] [SigmaCompactSpace M]
    [Subsingleton
      (DeRhamCohomology (I := I) (M := M) (A := ℝ) 1)]
    (U V : TopologicalSpace.Opens M) (hcover : U ⊔ V = ⊤)
    (phi : (U ⊓ V : TopologicalSpace.Opens M) ≃ₘ⟮I,
      AnnularCylinderModel⟯ Circle × ℝ)
    (v : Circle)
    (hleft : ¬ Subsingleton
      (DeRhamCohomology (I := I) (M := U) (A := ℝ) 1)) :
    Subsingleton
      (DeRhamCohomology (I := I) (M := V) (A := ℝ) 1) := by
  letI : Nontrivial
      (DeRhamCohomology (I := I) (M := U) (A := ℝ) 1) :=
    not_subsingleton_iff_nontrivial.mp hleft
  rcases exists_ne
      (0 : DeRhamCohomology (I := I) (M := U) (A := ℝ) 1) with
    ⟨tau, htau⟩
  let rho := deRhamCohomologyRestrictionOfLE
    (I := I) (A := ℝ)
    (W := (U ⊓ V : TopologicalSpace.Opens M)) (V := U)
    inf_le_left 1
  have hrho_tau : rho tau ≠ 0 := by
    intro hrho_tau_zero
    rcases deRham_mayerVietoris_longExact (A := ℝ) I U V hcover with ⟨LES⟩
    let zeroV : DeRhamCohomology (I := I) (M := V) (A := ℝ) 1 := 0
    have hdiff :
        deRhamMayerVietorisDifference (I := I) (A := ℝ) U V 1
            (tau, zeroV) = 0 := by
      change rho tau -
        deRhamCohomologyRestrictionOfLE (I := I) (A := ℝ)
          (W := (U ⊓ V : TopologicalSpace.Opens M)) (V := V)
          inf_le_right 1 0 = 0
      rw [hrho_tau_zero]
      rw [(deRhamCohomologyRestrictionOfLE (I := I) (A := ℝ)
        (W := (U ⊓ V : TopologicalSpace.Opens M)) (V := V)
        inf_le_right 1).map_zero]
      exact sub_self
        (0 : DeRhamCohomology (I := I)
          (M := (U ⊓ V : TopologicalSpace.Opens M)) (A := ℝ) 1)
    rcases (LES.exact_restriction_difference 1 (tau, zeroV)).mp hdiff with
      ⟨ambient, hambient⟩
    have hambient_zero : ambient = 0 := Subsingleton.elim _ _
    have hpair : (tau, zeroV) =
        (0 : DeRhamCohomology (I := I) (M := U) (A := ℝ) 1 ×
          DeRhamCohomology (I := I) (M := V) (A := ℝ) 1) := by
      calc
        (tau, 0) = deRhamMayerVietorisRestriction
            (I := I) (A := ℝ) U V 1 ambient := hambient.symm
        _ = deRhamMayerVietorisRestriction
            (I := I) (A := ℝ) U V 1 0 := congrArg _ hambient_zero
        _ = 0 := by
          apply Prod.ext
          · exact (deRhamCohomologyRestrictionToOpen
              (I := I) (M := M) (A := ℝ) U 1).map_zero
          · exact (deRhamCohomologyRestrictionToOpen
              (I := I) (M := M) (A := ℝ) V 1).map_zero
    exact htau (congrArg Prod.fst hpair)
  apply deRhamH1_subsingleton_of_mayerVietoris_left_restriction_surjective
    (A := ℝ) I U V hcover
  intro alpha
  rcases deRhamH1_eq_smul_of_diffeomorphic_annularCylinder
      I phi v (rho tau) hrho_tau alpha with ⟨c, hc⟩
  refine ⟨c • tau, ?_⟩
  rw [map_smul, ← hc]

end
end JJMath.Manifold
