import JJMath.Manifold.AnnularCohomology
import JJMath.Manifold.DeRhamMayerVietorisLinear

/-!
# The first de Rham cohomology of an annular cylinder

Two punctured-cylinder charts cover the cylinder. Their overlap has two
components, so its degree-zero cohomology is generated by a constant and a
locally constant step function. Mayer--Vietoris then shows that first de Rham
cohomology of the cylinder is generated by the connecting class of that step
function.
-/

open Set
open scoped Manifold ContDiff Topology

namespace JJMath.Manifold

noncomputable section

attribute [local instance] finrank_real_complex_fact'

/--
%%handwave
name:
  Pullback of a constant degree-zero de Rham class
statement:
  If \(\phi:M_1\to M_2\) is a diffeomorphism and \(c\in\mathbb R\), then
  \(\phi^*[c]=[c]\) in degree-zero de Rham cohomology.
proof:
  Pullback of the constant zero-form \(c\) is again the constant zero-form
  \(c\).
-/
theorem deRhamCohomologyPullbackDiffeomorph_constant
    {E₁ H₁ M₁ E₂ H₂ M₂ : Type*}
    [NormedAddCommGroup E₁] [NormedSpace ℝ E₁]
    [NormedAddCommGroup E₂] [NormedSpace ℝ E₂]
    [TopologicalSpace H₁] [TopologicalSpace M₁] [ChartedSpace H₁ M₁]
    [TopologicalSpace H₂] [TopologicalSpace M₂] [ChartedSpace H₂ M₂]
    (I₁ : ModelWithCorners ℝ E₁ H₁) (I₂ : ModelWithCorners ℝ E₂ H₂)
    [IsManifold I₁ ∞ M₁] [IsManifold I₂ ∞ M₂]
    (phi : M₁ ≃ₘ⟮I₁, I₂⟯ M₂) (c : ℝ) :
    deRhamCohomologyPullbackDiffeomorph I₁ I₂ phi 0
        (deRhamConstantH0Class (I0 := I₂) (M0 := M₂) c) =
      deRhamConstantH0Class (I0 := I₁) (M0 := M₁) c := by
  simp only [deRhamConstantH0Class, deRhamCohomologyPullbackDiffeomorph]
  apply congrArg
    (DeRhamExactClosedForms (I := I₁) (M := M₁) (A := ℝ) 0).mkQ
  apply Subtype.ext
  apply DifferentialForm.ext
  intro x
  ext v
  rfl

/--
%%handwave
name:
  Degree-zero cohomology of a manifold diffeomorphic to a convex open set
statement:
  If \(M\) is diffeomorphic to a nonempty convex open subset of a
  finite-dimensional real vector space, then every class in
  \(H_{\mathrm{dR}}^0(M;\mathbb R)\) is represented by a constant \(c\).
proof:
  Transport the class to the convex open set, where degree-zero de Rham
  cohomology consists of constants, and pull the resulting constant class
  back along the diffeomorphism.
-/
theorem deRhamH0_eq_constant_of_diffeomorphic_convex
    {E₁ H₁ M₁ E₂ : Type*}
    [NormedAddCommGroup E₁] [NormedSpace ℝ E₁]
    [NormedAddCommGroup E₂] [NormedSpace ℝ E₂] [FiniteDimensional ℝ E₂]
    [TopologicalSpace H₁] [TopologicalSpace M₁] [ChartedSpace H₁ M₁]
    (I₁ : ModelWithCorners ℝ E₁ H₁) [IsManifold I₁ ∞ M₁]
    (V : TopologicalSpace.Opens E₂) (hconvex : Convex ℝ (V : Set E₂))
    (x₀ : V) (phi : M₁ ≃ₘ⟮I₁, 𝓘(ℝ, E₂)⟯ V)
    (alpha : DeRhamCohomology (I := I₁) (M := M₁) (A := ℝ) 0) :
    ∃ c : ℝ,
      alpha = deRhamConstantH0Class (I0 := I₁) (M0 := M₁) c := by
  let beta := deRhamCohomologyPullbackDiffeomorph
    (𝓘(ℝ, E₂)) I₁ phi.symm 0 alpha
  rcases deRham_convex_open_H0_eq_constant V hconvex x₀ beta with ⟨c, hc⟩
  refine ⟨c, ?_⟩
  calc
    alpha = deRhamCohomologyPullbackDiffeomorph I₁ (𝓘(ℝ, E₂)) phi 0 beta :=
      (deRhamCohomologyPullbackDiffeomorph_comp_symm
        I₁ (𝓘(ℝ, E₂)) phi 0 alpha).symm
    _ = deRhamCohomologyPullbackDiffeomorph I₁ (𝓘(ℝ, E₂)) phi 0
          (deRhamConstantH0Class (I0 := 𝓘(ℝ, E₂)) (M0 := V) c) :=
      congrArg _ hc
    _ = deRhamConstantH0Class (I0 := I₁) (M0 := M₁) c :=
      deRhamCohomologyPullbackDiffeomorph_constant I₁ (𝓘(ℝ, E₂)) phi c

/--
%%handwave
name:
  Equality of closed zero-forms in degree-zero cohomology
statement:
  Two closed smooth zero-forms define the same degree-zero de Rham class if
  and only if they are equal.
proof:
  There are no differential forms of degree \(-1\), so the space of exact
  zero-forms is zero and the quotient map is injective.
-/
theorem deRhamH0_mkQ_eq_iff
    {E H M : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    [TopologicalSpace H] [TopologicalSpace M] [ChartedSpace H M]
    (I : ModelWithCorners ℝ E H) [IsManifold I ∞ M]
    (omega eta : DeRhamClosedForms (I := I) (M := M) (A := ℝ) 0) :
    (DeRhamExactClosedForms (I := I) (M := M) (A := ℝ) 0).mkQ omega =
        (DeRhamExactClosedForms (I := I) (M := M) (A := ℝ) 0).mkQ eta ↔
      omega = eta := by
  simp only [Submodule.mkQ_apply]
  rw [Submodule.Quotient.eq]
  simp [DeRhamExactClosedForms, DeRhamExactForms, sub_eq_zero]

set_option synthInstance.maxHeartbeats 100000 in
/--
%%handwave
name:
  Difference of constant degree-zero classes
statement:
  For \(c,d\in\mathbb R\), \([c]-[d]=[c-d]\) in
  \(H_{\mathrm{dR}}^0(M;\mathbb R)\).
proof:
  The quotient map is linear and subtraction of the two constant zero-forms
  is the constant zero-form \(c-d\).
-/
theorem deRhamConstantH0Class_sub
    {E H M : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    [TopologicalSpace H] [TopologicalSpace M] [ChartedSpace H M]
    (I : ModelWithCorners ℝ E H) [IsManifold I ∞ M]
    (c d : ℝ) :
    deRhamConstantH0Class (I0 := I) (M0 := M) c -
        deRhamConstantH0Class (I0 := I) (M0 := M) d =
      deRhamConstantH0Class (I0 := I) (M0 := M) (c - d) := by
  simp only [deRhamConstantH0Class, ← map_sub]
  apply congrArg
    (DeRhamExactClosedForms (I := I) (M := M) (A := ℝ) 0).mkQ
  apply Subtype.ext
  apply DifferentialForm.ext
  intro x
  ext q
  rw [show q = (fun i : Fin 0 => nomatch i) from Subsingleton.elim _ _]
  simp [deRhamConstantZeroClosedForm, smoothRealFunctionToZeroForm,
    smoothRealConstantFunction]
  change c - d = c - d
  rfl

def annularOpposite (v : Circle) : Circle :=
  (stereographic' 1 v).symm 0

/--
%%handwave
name:
  The antipodal chart point lies in the stereographic domain
statement:
  For \(v\in S^1\), the point whose stereographic coordinate relative to
  the puncture \(v\) is \(0\) belongs to the stereographic chart domain.
proof:
  The coordinate \(0\) lies in the chart target, so its inverse image lies in
  the source.
-/
theorem annularOpposite_mem_source (v : Circle) :
    annularOpposite v ∈ (stereographic' 1 v).source := by
  apply (stereographic' 1 v).map_target
  simp

/--
%%handwave
name:
  Stereographic coordinate of the antipodal chart point
statement:
  For \(v\in S^1\), the distinguished opposite point has stereographic
  coordinate \(0\) in the chart punctured at \(v\).
proof:
  It is defined as the inverse stereographic image of \(0\).
-/
theorem annularPunctureChart_opposite (v : Circle) :
    stereographic' 1 v (annularOpposite v) = 0 := by
  apply (stereographic' 1 v).right_inv
  simp

/--
%%handwave
name:
  Distinctness of a circle point and its stereographic opposite
statement:
  For every \(v\in S^1\), the point with stereographic coordinate \(0\)
  relative to \(v\) is different from \(v\).
proof:
  The stereographic chart source omits \(v\), while the opposite point belongs
  to that source.
-/
theorem annularOpposite_ne (v : Circle) : annularOpposite v ≠ v := by
  intro h
  have := annularOpposite_mem_source v
  rw [stereographic'_source] at this
  exact this h

/--
%%handwave
name:
  Vanishing criterion in one-dimensional Euclidean space
statement:
  A vector \(x\in\mathbb R^{\{0\}}\) is zero if and only if its unique
  coordinate \(x_0\) is zero.
proof:
  Equality of vectors is coordinatewise and there is only one coordinate.
-/
theorem euclideanFinOne_eq_zero_iff
    (x : EuclideanSpace ℝ (Fin 1)) : x = 0 ↔ x 0 = 0 := by
  constructor
  · intro h
    rw [h]
    rfl
  · intro h
    apply WithLp.ofLp_injective
    funext i
    fin_cases i
    exact h

/--
%%handwave
name:
  Zero stereographic coordinate characterizes the opposite point
statement:
  If \(x\) lies in the stereographic chart punctured at \(v\), then its
  stereographic coordinate is zero if and only if \(x\) is the distinguished
  opposite point.
proof:
  Injectivity of the stereographic chart compares \(x\) with the inverse image
  of \(0\).
-/
theorem stereographic_eq_zero_iff (v x : Circle)
    (hx : x ∈ (stereographic' 1 v).source) :
    stereographic' 1 v x = 0 ↔ x = annularOpposite v := by
  constructor
  · intro hzero
    apply (stereographic' 1 v).injOn hx (annularOpposite_mem_source v)
    rw [hzero, annularPunctureChart_opposite]
  · intro h
    rw [h, annularPunctureChart_opposite]

def annularPositiveTarget :
    TopologicalSpace.Opens (EuclideanSpace ℝ (Fin 1) × ℝ) where
  carrier := {p | 0 < p.1 0}
  is_open' := isOpen_lt continuous_const
    ((PiLp.continuous_apply 2 (fun _ : Fin 1 => ℝ) 0).comp continuous_fst)

def annularNegativeTarget :
    TopologicalSpace.Opens (EuclideanSpace ℝ (Fin 1) × ℝ) where
  carrier := {p | p.1 0 < 0}
  is_open' := isOpen_lt
    ((PiLp.continuous_apply 2 (fun _ : Fin 1 => ℝ) 0).comp continuous_fst)
    continuous_const

/--
%%handwave
name:
  Convexity of the positive annular chart target
statement:
  The half-space
  \(\{(x,t)\in\mathbb R\times\mathbb R:x>0\}\) is convex.
proof:
  It is an open half-space cut out by a linear functional.
-/
theorem annularPositiveTarget_convex :
    Convex ℝ (annularPositiveTarget : Set (EuclideanSpace ℝ (Fin 1) × ℝ)) := by
  change Convex ℝ {p : EuclideanSpace ℝ (Fin 1) × ℝ | 0 < p.1 0}
  apply convex_halfSpace_gt
  exact ⟨by intro x y; simp, by intro c x; simp⟩

/--
%%handwave
name:
  Convexity of the negative annular chart target
statement:
  The half-space
  \(\{(x,t)\in\mathbb R\times\mathbb R:x<0\}\) is convex.
proof:
  It is an open half-space cut out by a linear functional.
-/
theorem annularNegativeTarget_convex :
    Convex ℝ (annularNegativeTarget : Set (EuclideanSpace ℝ (Fin 1) × ℝ)) := by
  change Convex ℝ {p : EuclideanSpace ℝ (Fin 1) × ℝ | p.1 0 < 0}
  apply convex_halfSpace_lt
  exact ⟨by intro x y; simp, by intro c x; simp⟩

/--
%%handwave
name:
  Nonemptiness of the positive annular chart target
statement:
  The half-space \(\{(x,t):x>0\}\) is nonempty.
proof:
  It contains \((1,0)\).
-/
theorem annularPositiveTarget_nonempty :
    (annularPositiveTarget : Set (EuclideanSpace ℝ (Fin 1) × ℝ)).Nonempty := by
  refine ⟨(WithLp.toLp 2 (fun _ : Fin 1 => (1 : ℝ)), 0), ?_⟩
  simp [annularPositiveTarget]

/--
%%handwave
name:
  Nonemptiness of the negative annular chart target
statement:
  The half-space \(\{(x,t):x<0\}\) is nonempty.
proof:
  It contains \((-1,0)\).
-/
theorem annularNegativeTarget_nonempty :
    (annularNegativeTarget : Set (EuclideanSpace ℝ (Fin 1) × ℝ)).Nonempty := by
  refine ⟨(WithLp.toLp 2 (fun _ : Fin 1 => (-1 : ℝ)), 0), ?_⟩
  simp [annularNegativeTarget]

def annularPositiveComponent (v : Circle) :
    TopologicalSpace.Opens (Circle × ℝ) where
  carrier :=
    (deRham_boundarylessExtendedChart AnnularCylinderModel
      (annularPunctureChart v)).source ∩
      deRham_boundarylessExtendedChart AnnularCylinderModel
        (annularPunctureChart v) ⁻¹' annularPositiveTarget
  is_open' :=
    (deRham_boundarylessExtendedChart AnnularCylinderModel
      (annularPunctureChart v)).isOpen_inter_preimage annularPositiveTarget.2

def annularNegativeComponent (v : Circle) :
    TopologicalSpace.Opens (Circle × ℝ) where
  carrier :=
    (deRham_boundarylessExtendedChart AnnularCylinderModel
      (annularPunctureChart v)).source ∩
      deRham_boundarylessExtendedChart AnnularCylinderModel
        (annularPunctureChart v) ⁻¹' annularNegativeTarget
  is_open' :=
    (deRham_boundarylessExtendedChart AnnularCylinderModel
      (annularPunctureChart v)).isOpen_inter_preimage annularNegativeTarget.2

/--
%%handwave
name:
  Membership in the positive component of a doubly punctured cylinder
statement:
  A point \(p=(z,t)\in S^1\times\mathbb R\) belongs to the positive component
  determined by \(v\) if and only if \(z\ne v\) and the unique
  stereographic coordinate of \(z\) relative to \(v\) is positive.
proof:
  Expand the component as the chart source intersected with the inverse image
  of the positive half-space.
-/
theorem mem_annularPositiveComponent_iff (v : Circle) (p : Circle × ℝ) :
    p ∈ (annularPositiveComponent v : Set (Circle × ℝ)) ↔
      p.1 ≠ v ∧ 0 < (stereographic' 1 v p.1) 0 := by
  simp only [annularPositiveComponent]
  simp [annularPunctureChart, annularPositiveTarget, AnnularCylinderModel,
    deRham_boundarylessExtendedChart]
  intro hpos
  constructor
  · rintro ⟨hsource, _⟩
    change p.1 ∈ ({v}ᶜ : Set Circle) ∧ p.2 ∈ (Set.univ : Set ℝ) at hsource
    simpa using hsource.1
  · intro hpv
    constructor
    · change p.1 ∈ ({v}ᶜ : Set Circle) ∧ p.2 ∈ (Set.univ : Set ℝ)
      exact ⟨by simpa using hpv, Set.mem_univ _⟩
    · exact Set.mem_univ _

/--
%%handwave
name:
  Membership in the negative component of a doubly punctured cylinder
statement:
  A point \(p=(z,t)\in S^1\times\mathbb R\) belongs to the negative component
  determined by \(v\) if and only if \(z\ne v\) and the unique
  stereographic coordinate of \(z\) relative to \(v\) is negative.
proof:
  Expand the component as the chart source intersected with the inverse image
  of the negative half-space.
-/
theorem mem_annularNegativeComponent_iff (v : Circle) (p : Circle × ℝ) :
    p ∈ (annularNegativeComponent v : Set (Circle × ℝ)) ↔
      p.1 ≠ v ∧ (stereographic' 1 v p.1) 0 < 0 := by
  simp only [annularNegativeComponent]
  simp [annularPunctureChart, annularNegativeTarget, AnnularCylinderModel,
    deRham_boundarylessExtendedChart]
  intro hneg
  constructor
  · rintro ⟨hsource, _⟩
    change p.1 ∈ ({v}ᶜ : Set Circle) ∧ p.2 ∈ (Set.univ : Set ℝ) at hsource
    simpa using hsource.1
  · intro hpv
    constructor
    · change p.1 ∈ ({v}ᶜ : Set Circle) ∧ p.2 ∈ (Set.univ : Set ℝ)
      exact ⟨by simpa using hpv, Set.mem_univ _⟩
    · exact Set.mem_univ _

/--
%%handwave
name:
  Membership in a punctured annular cylinder
statement:
  A point \(p=(z,t)\in S^1\times\mathbb R\) lies in the cylinder punctured
  along \(\{v\}\times\mathbb R\) if and only if \(z\ne v\).
proof:
  The product chart source is
  \((S^1\setminus\{v\})\times\mathbb R\).
-/
theorem mem_annularPunctureOpen_iff (v : Circle) (p : Circle × ℝ) :
    p ∈ (annularPunctureOpen v : Set (Circle × ℝ)) ↔ p.1 ≠ v := by
  simp only [annularPunctureOpen, annularPunctureChart,
    OpenPartialHomeomorph.prod_source, stereographic'_source,
    OpenPartialHomeomorph.refl_source]
  change (p.1 ∈ ({v}ᶜ : Set Circle) ∧ p.2 ∈ (Set.univ : Set ℝ)) ↔ p.1 ≠ v
  simp

def annularDoublePunctureOpen (v : Circle) :
    TopologicalSpace.Opens (Circle × ℝ) :=
  annularPunctureOpen v ⊓ annularPunctureOpen (annularOpposite v)

/--
%%handwave
name:
  Components of the doubly punctured annular cylinder
statement:
  Removing the two distinguished circle points \(v\) and \(v^\ast\) from
  \(S^1\times\mathbb R\) leaves the union of the positive and negative
  stereographic-coordinate components.
proof:
  Away from \(v\), stereographic coordinates are defined; avoiding
  \(v^\ast\) makes the coordinate nonzero, hence either positive or negative.
-/
theorem annularComponents_cover_doublePuncture (v : Circle) :
    annularPositiveComponent v ⊔ annularNegativeComponent v =
      annularDoublePunctureOpen v := by
  apply le_antisymm
  · apply sup_le
    · intro p hp
      have hpSet : p ∈ (annularPositiveComponent v : Set (Circle × ℝ)) := hp
      rw [mem_annularPositiveComponent_iff] at hpSet
      change p ∈ annularPunctureOpen v ∧
        p ∈ annularPunctureOpen (annularOpposite v)
      have hpv : p ∈ annularPunctureOpen v :=
        (mem_annularPunctureOpen_iff v p).mpr hpSet.1
      refine ⟨hpv, ?_⟩
      apply (mem_annularPunctureOpen_iff (annularOpposite v) p).mpr
      intro hopposite
      rw [hopposite, annularPunctureChart_opposite] at hpSet
      have : (0 : ℝ) < 0 := by simpa using hpSet.2
      exact (lt_irrefl 0) this
    · intro p hp
      have hpSet : p ∈ (annularNegativeComponent v : Set (Circle × ℝ)) := hp
      rw [mem_annularNegativeComponent_iff] at hpSet
      change p ∈ annularPunctureOpen v ∧
        p ∈ annularPunctureOpen (annularOpposite v)
      have hpv : p ∈ annularPunctureOpen v :=
        (mem_annularPunctureOpen_iff v p).mpr hpSet.1
      refine ⟨hpv, ?_⟩
      apply (mem_annularPunctureOpen_iff (annularOpposite v) p).mpr
      intro hopposite
      rw [hopposite, annularPunctureChart_opposite] at hpSet
      have : (0 : ℝ) < 0 := by simpa using hpSet.2
      exact (lt_irrefl 0) this
  · intro p hp
    change p ∈ annularPunctureOpen v ∧
      p ∈ annularPunctureOpen (annularOpposite v) at hp
    have hp' : p.1 ≠ v ∧ p.1 ≠ annularOpposite v := by
      exact ⟨(mem_annularPunctureOpen_iff v p).mp hp.1,
        (mem_annularPunctureOpen_iff (annularOpposite v) p).mp hp.2⟩
    change p ∈ annularPositiveComponent v ∨ p ∈ annularNegativeComponent v
    have hsource : p.1 ∈ (stereographic' 1 v).source := by
      simpa [stereographic'_source] using hp'.1
    have hcoord : (stereographic' 1 v p.1) 0 ≠ 0 := by
      intro hzero
      apply hp'.2
      apply (stereographic_eq_zero_iff v p.1 hsource).mp
      exact (euclideanFinOne_eq_zero_iff _).mpr hzero
    rcases lt_or_gt_of_ne hcoord with hneg | hpos
    · right
      show p ∈ (annularNegativeComponent v : Set (Circle × ℝ))
      exact (mem_annularNegativeComponent_iff v p).mpr ⟨hp'.1, hneg⟩
    · left
      show p ∈ (annularPositiveComponent v : Set (Circle × ℝ))
      exact (mem_annularPositiveComponent_iff v p).mpr ⟨hp'.1, hpos⟩

/--
%%handwave
name:
  Disjointness of the annular overlap components
statement:
  The positive and negative components of the doubly punctured annular
  cylinder are disjoint.
proof:
  Their defining stereographic coordinate cannot be simultaneously positive
  and negative.
-/
theorem annularComponents_disjoint (v : Circle) :
    annularPositiveComponent v ⊓ annularNegativeComponent v = ⊥ := by
  apply le_antisymm
  · intro p hp
    change p ∈ annularPositiveComponent v ∧ p ∈ annularNegativeComponent v at hp
    have hpPos : p ∈ (annularPositiveComponent v : Set (Circle × ℝ)) := hp.1
    have hpNeg : p ∈ (annularNegativeComponent v : Set (Circle × ℝ)) := hp.2
    rw [mem_annularPositiveComponent_iff] at hpPos
    rw [mem_annularNegativeComponent_iff] at hpNeg
    have : False := by linarith [hpPos.2, hpNeg.2]
    exact this.elim
  · intro p hp
    change p ∈ (∅ : Set (Circle × ℝ)) at hp
    exact hp.elim

/--
%%handwave
name:
  Positive component lies in the doubly punctured cylinder
statement:
  The positive stereographic component is contained in the cylinder punctured
  at \(v\) and \(v^\ast\).
proof:
  It is one member of the two-component cover of the doubly punctured
  cylinder.
-/
theorem annularPositiveComponent_le_doublePuncture (v : Circle) :
    annularPositiveComponent v ≤ annularDoublePunctureOpen v := by
  rw [← annularComponents_cover_doublePuncture v]
  exact le_sup_left

/--
%%handwave
name:
  Negative component lies in the doubly punctured cylinder
statement:
  The negative stereographic component is contained in the cylinder punctured
  at \(v\) and \(v^\ast\).
proof:
  It is one member of the two-component cover of the doubly punctured
  cylinder.
-/
theorem annularNegativeComponent_le_doublePuncture (v : Circle) :
    annularNegativeComponent v ≤ annularDoublePunctureOpen v := by
  rw [← annularComponents_cover_doublePuncture v]
  exact le_sup_right

def annularOverlapPositiveSet (v : Circle) :
    Set (annularDoublePunctureOpen v) :=
  {x | (x.1 : Circle × ℝ) ∈ (annularPositiveComponent v : Set (Circle × ℝ))}

/--
%%handwave
name:
  The positive overlap component is clopen
statement:
  Inside the doubly punctured annular cylinder, the positive component is
  both open and closed.
proof:
  It is open by construction, and its complement is exactly the negative
  component, which is also open.
-/
theorem annularOverlapPositiveSet_isClopen (v : Circle) :
    IsClopen (annularOverlapPositiveSet v) := by
  have hopen : IsOpen (annularOverlapPositiveSet v) :=
    (annularPositiveComponent v).2.preimage continuous_subtype_val
  refine ⟨?_, hopen⟩
  rw [← isOpen_compl_iff]
  have heq : (annularOverlapPositiveSet v)ᶜ =
      {x : annularDoublePunctureOpen v |
        (x.1 : Circle × ℝ) ∈
          (annularNegativeComponent v : Set (Circle × ℝ))} := by
    ext x
    change
      (¬(x.1 : Circle × ℝ) ∈
        (annularPositiveComponent v : Set (Circle × ℝ))) ↔
      (x.1 : Circle × ℝ) ∈
        (annularNegativeComponent v : Set (Circle × ℝ))
    rw [mem_annularPositiveComponent_iff,
      mem_annularNegativeComponent_iff]
    have hxpuncture :
        (x.1 : Circle × ℝ).1 ≠ v ∧
          (x.1 : Circle × ℝ).1 ≠ annularOpposite v := by
      have hxproperty := x.property
      change (x.1 : Circle × ℝ) ∈ annularPunctureOpen v ∧
        (x.1 : Circle × ℝ) ∈ annularPunctureOpen (annularOpposite v) at hxproperty
      exact ⟨(mem_annularPunctureOpen_iff v x.1).mp hxproperty.1,
        (mem_annularPunctureOpen_iff (annularOpposite v) x.1).mp hxproperty.2⟩
    have hsource : (x.1 : Circle × ℝ).1 ∈ (stereographic' 1 v).source := by
      simpa [stereographic'_source] using hxpuncture.1
    have hcoord :
        (stereographic' 1 v (x.1 : Circle × ℝ).1) 0 ≠ 0 := by
      intro hzero
      apply hxpuncture.2
      apply (stereographic_eq_zero_iff v _ hsource).mp
      exact (euclideanFinOne_eq_zero_iff _).mpr hzero
    constructor
    · intro hnot
      refine ⟨hxpuncture.1, ?_⟩
      have hnpos : ¬0 < (stereographic' 1 v (x.1 : Circle × ℝ).1) 0 :=
        fun hpos => hnot ⟨hxpuncture.1, hpos⟩
      exact lt_of_le_of_ne (le_of_not_gt hnpos) hcoord
    · rintro ⟨_, hneg⟩ ⟨_, hpos⟩
      linarith
  rw [heq]
  exact (annularNegativeComponent v).2.preimage continuous_subtype_val

noncomputable def annularOverlapStepFunction (v : Circle)
    (x : annularDoublePunctureOpen v) : ℝ :=
  by
    classical
    exact if x ∈ annularOverlapPositiveSet v then 1 else 0

/--
%%handwave
name:
  Local constancy of the annular overlap step
statement:
  The function on the doubly punctured cylinder that equals \(1\) on the
  positive component and \(0\) on the negative component is locally constant.
proof:
  The positive component and its complement are both open, so the function is
  constant on a neighborhood of every point.
-/
theorem annularOverlapStepFunction_isLocallyConstant (v : Circle) :
    IsLocallyConstant (annularOverlapStepFunction v) := by
  classical
  rw [IsLocallyConstant.iff_eventually_eq]
  intro x
  by_cases hx : x ∈ annularOverlapPositiveSet v
  · filter_upwards [(annularOverlapPositiveSet_isClopen v).2.mem_nhds hx] with y hy
    simp [annularOverlapStepFunction, hx, hy]
  · have hxc : x ∈ (annularOverlapPositiveSet v)ᶜ := hx
    filter_upwards [((annularOverlapPositiveSet_isClopen v).1.isOpen_compl.mem_nhds hxc)]
      with y hy
    have hynot : y ∉ annularOverlapPositiveSet v := hy
    simp [annularOverlapStepFunction, hx, hynot]

noncomputable def annularOverlapStepClosedForm (v : Circle) :
    DeRhamClosedForms (I := AnnularCylinderModel)
      (M := annularDoublePunctureOpen v) (A := ℝ) 0 :=
  ⟨smoothRealFunctionToZeroForm (I0 := AnnularCylinderModel)
      (smoothRealFunctionOfIsLocallyConstant AnnularCylinderModel
        (annularOverlapStepFunction v)
        (annularOverlapStepFunction_isLocallyConstant v)),
    deRhamDifferential_locallyConstant_zeroForm_eq_zero
      (I0 := AnnularCylinderModel) (annularOverlapStepFunction v)
      (annularOverlapStepFunction_isLocallyConstant v)⟩

noncomputable def annularOverlapStepClass (v : Circle) :
    DeRhamCohomology (I := AnnularCylinderModel)
      (M := annularDoublePunctureOpen v) (A := ℝ) 0 :=
  (DeRhamExactClosedForms (I := AnnularCylinderModel)
    (M := annularDoublePunctureOpen v) (A := ℝ) 0).mkQ
      (annularOverlapStepClosedForm v)

/--
%%handwave
name:
  Restriction of the annular overlap step to the positive component
statement:
  The locally constant closed zero-form defined by the annular overlap step
  restricts to the constant zero-form \(1\) on the positive component.
proof:
  Every point of that component satisfies the positive branch of the step
  function.
-/
theorem annularOverlapStepClosedForm_restrict_positive (v : Circle) :
    deRhamClosedFormsRestrictionOfLE (I := AnnularCylinderModel) (A := ℝ)
        (annularPositiveComponent_le_doublePuncture v) 0
        (annularOverlapStepClosedForm v) =
      deRhamConstantZeroClosedForm (I0 := AnnularCylinderModel)
        (M0 := annularPositiveComponent v) 1 := by
  classical
  apply Subtype.ext
  apply DifferentialForm.ext
  intro x
  ext q
  rw [show q = (fun i : Fin 0 => nomatch i) from Subsingleton.elim _ _]
  simp only [deRhamClosedFormsRestrictionOfLE, restrictSmoothFormsOfLE,
    annularOverlapStepClosedForm,
    smoothRealFunctionToZeroForm, smoothRealFunctionOfIsLocallyConstant,
    deRhamConstantZeroClosedForm, smoothRealConstantFunction,
    ContinuousAlternatingMap.constOfIsEmpty_apply]
  have hx : TopologicalSpace.Opens.inclusion
      (annularPositiveComponent_le_doublePuncture v) x ∈
        annularOverlapPositiveSet v := x.property
  change
    (if TopologicalSpace.Opens.inclusion
        (annularPositiveComponent_le_doublePuncture v) x ∈
          annularOverlapPositiveSet v then 1 else 0) = 1
  simp [hx]

/--
%%handwave
name:
  Restriction of the annular overlap step to the negative component
statement:
  The annular overlap step zero-form restricts to the constant zero-form
  \(0\) on the negative component.
proof:
  The positive and negative components are disjoint, so every point of the
  negative component satisfies the zero branch.
-/
theorem annularOverlapStepClosedForm_restrict_negative (v : Circle) :
    deRhamClosedFormsRestrictionOfLE (I := AnnularCylinderModel) (A := ℝ)
        (annularNegativeComponent_le_doublePuncture v) 0
        (annularOverlapStepClosedForm v) =
      deRhamConstantZeroClosedForm (I0 := AnnularCylinderModel)
        (M0 := annularNegativeComponent v) 0 := by
  classical
  apply Subtype.ext
  apply DifferentialForm.ext
  intro x
  ext q
  rw [show q = (fun i : Fin 0 => nomatch i) from Subsingleton.elim _ _]
  simp only [deRhamClosedFormsRestrictionOfLE, restrictSmoothFormsOfLE,
    annularOverlapStepClosedForm,
    smoothRealFunctionToZeroForm, smoothRealFunctionOfIsLocallyConstant,
    deRhamConstantZeroClosedForm, smoothRealConstantFunction,
    ContinuousAlternatingMap.constOfIsEmpty_apply]
  have hx : TopologicalSpace.Opens.inclusion
      (annularNegativeComponent_le_doublePuncture v) x ∉
        annularOverlapPositiveSet v := by
    intro hxpos
    have hxPosAmbient : (x.1 : Circle × ℝ) ∈
        (annularPositiveComponent v : Set (Circle × ℝ)) := hxpos
    have hxNegAmbient : (x.1 : Circle × ℝ) ∈
        (annularNegativeComponent v : Set (Circle × ℝ)) := x.property
    have hmem : (x.1 : Circle × ℝ) ∈
        (annularPositiveComponent v ⊓ annularNegativeComponent v :
          TopologicalSpace.Opens (Circle × ℝ)) := ⟨hxPosAmbient, hxNegAmbient⟩
    rw [annularComponents_disjoint v] at hmem
    exact hmem
  change
    (if TopologicalSpace.Opens.inclusion
        (annularNegativeComponent_le_doublePuncture v) x ∈
          annularOverlapPositiveSet v then 1 else 0) = 0
  simp [hx]

/--
%%handwave
name:
  Positive restriction of the annular overlap step class
statement:
  The degree-zero cohomology class of the annular overlap step restricts to
  the constant class \([1]\) on the positive component.
proof:
  Restriction commutes with passage to cohomology, and the representing
  zero-form restricts to the constant form \(1\).
-/
theorem annularOverlapStepClass_restrict_positive (v : Circle) :
    deRhamCohomologyRestrictionOfLE (I := AnnularCylinderModel) (A := ℝ)
        (annularPositiveComponent_le_doublePuncture v) 0
        (annularOverlapStepClass v) =
      deRhamConstantH0Class (I0 := AnnularCylinderModel)
        (M0 := annularPositiveComponent v) 1 := by
  simp only [annularOverlapStepClass, deRhamCohomologyRestrictionOfLE,
    deRhamConstantH0Class]
  change
    (DeRhamExactClosedForms (I := AnnularCylinderModel)
      (M := annularPositiveComponent v) (A := ℝ) 0).mkQ
        (deRhamClosedFormsRestrictionOfLE (I := AnnularCylinderModel) (A := ℝ)
          (annularPositiveComponent_le_doublePuncture v) 0
          (annularOverlapStepClosedForm v)) = _
  rw [annularOverlapStepClosedForm_restrict_positive]

/--
%%handwave
name:
  Negative restriction of the annular overlap step class
statement:
  The degree-zero cohomology class of the annular overlap step restricts to
  the constant class \([0]\) on the negative component.
proof:
  Restriction commutes with passage to cohomology, and the representing
  zero-form restricts to zero.
-/
theorem annularOverlapStepClass_restrict_negative (v : Circle) :
    deRhamCohomologyRestrictionOfLE (I := AnnularCylinderModel) (A := ℝ)
        (annularNegativeComponent_le_doublePuncture v) 0
        (annularOverlapStepClass v) =
      deRhamConstantH0Class (I0 := AnnularCylinderModel)
        (M0 := annularNegativeComponent v) 0 := by
  simp only [annularOverlapStepClass, deRhamCohomologyRestrictionOfLE,
    deRhamConstantH0Class]
  change
    (DeRhamExactClosedForms (I := AnnularCylinderModel)
      (M := annularNegativeComponent v) (A := ℝ) 0).mkQ
        (deRhamClosedFormsRestrictionOfLE (I := AnnularCylinderModel) (A := ℝ)
          (annularNegativeComponent_le_doublePuncture v) 0
          (annularOverlapStepClosedForm v)) = _
  rw [annularOverlapStepClosedForm_restrict_negative]

/--
%%handwave
name:
  Positive annular overlap component as a half-space
statement:
  For every \(v\in S^1\), the positive component of the doubly punctured
  annular cylinder is diffeomorphic to the half-space
  \(\{(x,t)\in\mathbb R^2:x>0\}\).
proof:
  Restrict the product stereographic chart punctured at \(v\) to the inverse
  image of the positive target half-space.
-/
theorem annularPositiveComponent_diffeomorph (v : Circle) :
    Nonempty
      (annularPositiveComponent v ≃ₘ⟮AnnularCylinderModel,
        𝓘(ℝ, EuclideanSpace ℝ (Fin 1) × ℝ)⟯ annularPositiveTarget) := by
  apply deRham_boundarylessExtendedChart_restriction_diffeomorph
    AnnularCylinderModel
    (e := annularPunctureChart v)
    (annularPunctureChart_mem_atlas v)
  · rfl
  · intro y hy
    change y ∈ ((annularPunctureChart v).extend AnnularCylinderModel).target
    rw [OpenPartialHomeomorph.extend_target]
    simp [annularPunctureChart, AnnularCylinderModel]
    exact Set.mem_univ y

/--
%%handwave
name:
  Negative annular overlap component as a half-space
statement:
  For every \(v\in S^1\), the negative component of the doubly punctured
  annular cylinder is diffeomorphic to
  \(\{(x,t)\in\mathbb R^2:x<0\}\).
proof:
  Restrict the product stereographic chart punctured at \(v\) to the inverse
  image of the negative target half-space.
-/
theorem annularNegativeComponent_diffeomorph (v : Circle) :
    Nonempty
      (annularNegativeComponent v ≃ₘ⟮AnnularCylinderModel,
        𝓘(ℝ, EuclideanSpace ℝ (Fin 1) × ℝ)⟯ annularNegativeTarget) := by
  apply deRham_boundarylessExtendedChart_restriction_diffeomorph
    AnnularCylinderModel
    (e := annularPunctureChart v)
    (annularPunctureChart_mem_atlas v)
  · rfl
  · intro y hy
    change y ∈ ((annularPunctureChart v).extend AnnularCylinderModel).target
    rw [OpenPartialHomeomorph.extend_target]
    simp [annularPunctureChart, AnnularCylinderModel]
    exact Set.mem_univ y

/--
%%handwave
name:
  Nonemptiness of the positive annular overlap component
statement:
  The positive component of the doubly punctured annular cylinder is
  nonempty.
proof:
  Its diffeomorphic positive half-space target contains \((1,0)\).
-/
theorem annularPositiveComponent_nonempty (v : Circle) :
    Nonempty (annularPositiveComponent v) := by
  rcases annularPositiveComponent_diffeomorph v with ⟨phi⟩
  exact ⟨phi.symm ⟨annularPositiveTarget_nonempty.choose,
    annularPositiveTarget_nonempty.choose_spec⟩⟩

/--
%%handwave
name:
  Nonemptiness of the negative annular overlap component
statement:
  The negative component of the doubly punctured annular cylinder is
  nonempty.
proof:
  Its diffeomorphic negative half-space target contains \((-1,0)\).
-/
theorem annularNegativeComponent_nonempty (v : Circle) :
    Nonempty (annularNegativeComponent v) := by
  rcases annularNegativeComponent_diffeomorph v with ⟨phi⟩
  exact ⟨phi.symm ⟨annularNegativeTarget_nonempty.choose,
    annularNegativeTarget_nonempty.choose_spec⟩⟩

/--
%%handwave
name:
  Degree-zero cohomology of a singly punctured annular cylinder
statement:
  Every class in the degree-zero de Rham cohomology of
  \((S^1\setminus\{v\})\times\mathbb R\) is a constant class \([c]\).
proof:
  The punctured cylinder is diffeomorphic to a nonempty convex open subset of
  a Euclidean space, whose degree-zero cohomology consists of constants.
-/
theorem annularPuncture_H0_eq_constant (v : Circle)
    (alpha : DeRhamCohomology (I := AnnularCylinderModel)
      (M := annularPunctureOpen v) (A := ℝ) 0) :
    ∃ c : ℝ, alpha = deRhamConstantH0Class
      (I0 := AnnularCylinderModel) (M0 := annularPunctureOpen v) c := by
  rcases annularPuncture_diffeomorphic_convex v with
    ⟨V, hconvex, hne, ⟨phi⟩⟩
  exact deRhamH0_eq_constant_of_diffeomorphic_convex
    AnnularCylinderModel V hconvex ⟨hne.choose, hne.choose_spec⟩ phi alpha

/--
%%handwave
name:
  Degree-zero cohomology of the positive annular component
statement:
  Every degree-zero de Rham class on the positive overlap component is a
  constant class \([c]\).
proof:
  The component is diffeomorphic to a nonempty convex positive half-space.
-/
theorem annularPositiveComponent_H0_eq_constant (v : Circle)
    (alpha : DeRhamCohomology (I := AnnularCylinderModel)
      (M := annularPositiveComponent v) (A := ℝ) 0) :
    ∃ c : ℝ, alpha = deRhamConstantH0Class
      (I0 := AnnularCylinderModel) (M0 := annularPositiveComponent v) c := by
  rcases annularPositiveComponent_diffeomorph v with ⟨phi⟩
  exact deRhamH0_eq_constant_of_diffeomorphic_convex
    AnnularCylinderModel annularPositiveTarget annularPositiveTarget_convex
    ⟨_, annularPositiveTarget_nonempty.choose_spec⟩ phi alpha

/--
%%handwave
name:
  Degree-zero cohomology of the negative annular component
statement:
  Every degree-zero de Rham class on the negative overlap component is a
  constant class \([c]\).
proof:
  The component is diffeomorphic to a nonempty convex negative half-space.
-/
theorem annularNegativeComponent_H0_eq_constant (v : Circle)
    (alpha : DeRhamCohomology (I := AnnularCylinderModel)
      (M := annularNegativeComponent v) (A := ℝ) 0) :
    ∃ c : ℝ, alpha = deRhamConstantH0Class
      (I0 := AnnularCylinderModel) (M0 := annularNegativeComponent v) c := by
  rcases annularNegativeComponent_diffeomorph v with ⟨phi⟩
  exact deRhamH0_eq_constant_of_diffeomorphic_convex
    AnnularCylinderModel annularNegativeTarget annularNegativeTarget_convex
    ⟨_, annularNegativeTarget_nonempty.choose_spec⟩ phi alpha

set_option synthInstance.maxHeartbeats 100000 in
/--
%%handwave
name:
  Degree-zero cohomology of the doubly punctured annular cylinder
statement:
  Every class \(\alpha\) on the doubly punctured cylinder has the form
  \[
    \alpha=[c]+d[s],
  \]
  where \(s\) is the locally constant function equal to \(1\) on the positive
  component and \(0\) on the negative component.
proof:
  Restrict \(\alpha\) to the two components, obtaining constants
  \(c_+\) and \(c_-\).  The class
  \([c_-]+(c_+-c_-)[s]\) has the same restriction on both components, hence
  equals \(\alpha\).
-/
theorem annularDoublePuncture_H0_eq_constant_add_smul_step
    (v : Circle)
    (alpha : DeRhamCohomology (I := AnnularCylinderModel)
      (M := annularDoublePunctureOpen v) (A := ℝ) 0) :
    ∃ c d : ℝ,
      alpha =
        deRhamConstantH0Class (I0 := AnnularCylinderModel)
            (M0 := annularDoublePunctureOpen v) c +
          d • annularOverlapStepClass v := by
  classical
  induction alpha using Submodule.Quotient.induction_on with
  | _ omega =>
      let alphaPos :=
        deRhamCohomologyRestrictionOfLE (I := AnnularCylinderModel) (A := ℝ)
          (annularPositiveComponent_le_doublePuncture v) 0
          ((DeRhamExactClosedForms (I := AnnularCylinderModel)
            (M := annularDoublePunctureOpen v) (A := ℝ) 0).mkQ omega)
      let alphaNeg :=
        deRhamCohomologyRestrictionOfLE (I := AnnularCylinderModel) (A := ℝ)
          (annularNegativeComponent_le_doublePuncture v) 0
          ((DeRhamExactClosedForms (I := AnnularCylinderModel)
            (M := annularDoublePunctureOpen v) (A := ℝ) 0).mkQ omega)
      rcases annularPositiveComponent_H0_eq_constant v alphaPos with ⟨cPos, hcPos⟩
      rcases annularNegativeComponent_H0_eq_constant v alphaNeg with ⟨cNeg, hcNeg⟩
      refine ⟨cNeg, cPos - cNeg, ?_⟩
      have hcPos' :
          (DeRhamExactClosedForms (I := AnnularCylinderModel)
            (M := annularPositiveComponent v) (A := ℝ) 0).mkQ
              (deRhamClosedFormsRestrictionOfLE
                (I := AnnularCylinderModel) (A := ℝ)
                (annularPositiveComponent_le_doublePuncture v) 0 omega) =
            (DeRhamExactClosedForms (I := AnnularCylinderModel)
              (M := annularPositiveComponent v) (A := ℝ) 0).mkQ
                (deRhamConstantZeroClosedForm (I0 := AnnularCylinderModel)
                  (M0 := annularPositiveComponent v) cPos) := by
        simpa [alphaPos, deRhamCohomologyRestrictionOfLE,
          deRhamConstantH0Class] using hcPos
      have hcNeg' :
          (DeRhamExactClosedForms (I := AnnularCylinderModel)
            (M := annularNegativeComponent v) (A := ℝ) 0).mkQ
              (deRhamClosedFormsRestrictionOfLE
                (I := AnnularCylinderModel) (A := ℝ)
                (annularNegativeComponent_le_doublePuncture v) 0 omega) =
            (DeRhamExactClosedForms (I := AnnularCylinderModel)
              (M := annularNegativeComponent v) (A := ℝ) 0).mkQ
                (deRhamConstantZeroClosedForm (I0 := AnnularCylinderModel)
                  (M0 := annularNegativeComponent v) cNeg) := by
        simpa [alphaNeg, deRhamCohomologyRestrictionOfLE,
          deRhamConstantH0Class] using hcNeg
      have hcPosClosed :=
        (deRhamH0_mkQ_eq_iff AnnularCylinderModel _ _).mp hcPos'
      have hcNegClosed :=
        (deRhamH0_mkQ_eq_iff AnnularCylinderModel _ _).mp hcNeg'
      have hforms :
          omega =
            deRhamConstantZeroClosedForm (I0 := AnnularCylinderModel)
                (M0 := annularDoublePunctureOpen v) cNeg +
              (cPos - cNeg) • annularOverlapStepClosedForm v := by
        apply Subtype.ext
        apply DifferentialForm.ext
        intro x
        ext q
        rw [show q = (fun i : Fin 0 => nomatch i) from Subsingleton.elim _ _]
        have hxcover : (x.1 : Circle × ℝ) ∈
            (annularPositiveComponent v : Set (Circle × ℝ)) ∨
          (x.1 : Circle × ℝ) ∈
            (annularNegativeComponent v : Set (Circle × ℝ)) := by
          have hx : (x.1 : Circle × ℝ) ∈
              (annularPositiveComponent v ⊔ annularNegativeComponent v :
                TopologicalSpace.Opens (Circle × ℝ)) := by
            rw [annularComponents_cover_doublePuncture v]
            exact x.property
          exact hx
        rcases hxcover with hxPos | hxNeg
        · let xPos : annularPositiveComponent v := ⟨x.1, hxPos⟩
          have hvalue := congrArg
            (fun eta : DeRhamClosedForms (I := AnnularCylinderModel)
                (M := annularPositiveComponent v) (A := ℝ) 0 =>
              eta.1.toFun xPos (fun i : Fin 0 => nomatch i)) hcPosClosed
          have harg :
              (mfderiv AnnularCylinderModel AnnularCylinderModel
                  (TopologicalSpace.Opens.inclusion
                    (annularPositiveComponent_le_doublePuncture v)) xPos ∘
                (fun i : Fin 0 => nomatch i)) =
              (fun i : Fin 0 => nomatch i) := Subsingleton.elim _ _
          have hvalue' :
              omega.1.toFun x (fun i : Fin 0 => nomatch i) = cPos := by
            simpa [xPos, deRhamClosedFormsRestrictionOfLE,
              restrictSmoothFormsOfLE, restrictSmoothFormOfLE,
              deRhamConstantZeroClosedForm, smoothRealFunctionToZeroForm,
              smoothRealConstantFunction, harg] using hvalue
          have hxStep : x ∈ annularOverlapPositiveSet v := hxPos
          simp only [deRhamConstantZeroClosedForm, annularOverlapStepClosedForm,
            smoothRealFunctionToZeroForm, smoothRealConstantFunction,
            smoothRealFunctionOfIsLocallyConstant]
          change omega.1.toFun x (fun i : Fin 0 => nomatch i) =
            cNeg + (cPos - cNeg) *
              (if x ∈ annularOverlapPositiveSet v then 1 else 0)
          rw [if_pos hxStep, hvalue']
          ring
        · let xNeg : annularNegativeComponent v := ⟨x.1, hxNeg⟩
          have hvalue := congrArg
            (fun eta : DeRhamClosedForms (I := AnnularCylinderModel)
                (M := annularNegativeComponent v) (A := ℝ) 0 =>
              eta.1.toFun xNeg (fun i : Fin 0 => nomatch i)) hcNegClosed
          have harg :
              (mfderiv AnnularCylinderModel AnnularCylinderModel
                  (TopologicalSpace.Opens.inclusion
                    (annularNegativeComponent_le_doublePuncture v)) xNeg ∘
                (fun i : Fin 0 => nomatch i)) =
              (fun i : Fin 0 => nomatch i) := Subsingleton.elim _ _
          have hvalue' :
              omega.1.toFun x (fun i : Fin 0 => nomatch i) = cNeg := by
            simpa [xNeg, deRhamClosedFormsRestrictionOfLE,
              restrictSmoothFormsOfLE, restrictSmoothFormOfLE,
              deRhamConstantZeroClosedForm, smoothRealFunctionToZeroForm,
              smoothRealConstantFunction, harg] using hvalue
          have hxStep : x ∉ annularOverlapPositiveSet v := by
            intro hxPos
            have hmem : (x.1 : Circle × ℝ) ∈
                (annularPositiveComponent v ⊓ annularNegativeComponent v :
                  TopologicalSpace.Opens (Circle × ℝ)) := ⟨hxPos, hxNeg⟩
            rw [annularComponents_disjoint v] at hmem
            exact hmem
          simp only [deRhamConstantZeroClosedForm, annularOverlapStepClosedForm,
            smoothRealFunctionToZeroForm, smoothRealConstantFunction,
            smoothRealFunctionOfIsLocallyConstant]
          change omega.1.toFun x (fun i : Fin 0 => nomatch i) =
            cNeg + (cPos - cNeg) *
              (if x ∈ annularOverlapPositiveSet v then 1 else 0)
          rw [if_neg hxStep, hvalue']
          ring
      have hquot := congrArg
        (DeRhamExactClosedForms (I := AnnularCylinderModel)
          (M := annularDoublePunctureOpen v) (A := ℝ) 0).mkQ hforms
      simpa only [deRhamConstantH0Class, annularOverlapStepClass,
        map_add, map_smul] using hquot

/--
%%handwave
name:
  Cover of the annular cylinder by two punctures
statement:
  The two open cylinders obtained by removing \(v\) and its distinguished
  opposite \(v^\ast\) cover \(S^1\times\mathbb R\).
proof:
  Since \(v\ne v^\ast\), a circle point cannot equal both punctures.
-/
theorem annularPunctures_cover (v : Circle) :
    annularPunctureOpen v ⊔ annularPunctureOpen (annularOpposite v) = ⊤ := by
  ext p
  constructor
  · intro
    trivial
  · intro
    change p ∈ annularPunctureOpen v ∨
      p ∈ annularPunctureOpen (annularOpposite v)
    by_cases hp : p.1 = v
    · right
      apply (mem_annularPunctureOpen_iff (annularOpposite v) p).mpr
      rw [hp]
      exact (annularOpposite_ne v).symm
    · left
      exact (mem_annularPunctureOpen_iff v p).mpr hp

noncomputable def annularStepConnectingClass (v : Circle) :
    DeRhamCohomology (I := AnnularCylinderModel)
      (M := Circle × ℝ) (A := ℝ) 1 :=
  deRhamMayerVietorisConnectingOfPartitionOfUnity (A := ℝ)
    AnnularCylinderModel (annularPunctureOpen v)
      (annularPunctureOpen (annularOpposite v)) (annularPunctures_cover v) 0
      (annularOverlapStepClass v)

set_option synthInstance.maxHeartbeats 100000 in
set_option maxHeartbeats 800000 in
/--
%%handwave
name:
  Generation of annular first cohomology by the connecting step class
statement:
  Every class \(\alpha\in H_{\mathrm{dR}}^1(S^1\times\mathbb R;\mathbb R)\)
  is a scalar multiple of the Mayer--Vietoris connecting class of the overlap
  step function.
proof:
  On each singly punctured cylinder, first cohomology vanishes, so exactness
  puts \(\alpha\) in the image of the connecting map.  Decompose its
  degree-zero overlap preimage into a constant plus a multiple of the step;
  exactness kills the constant part and leaves the asserted multiple.
-/
theorem annularCylinder_deRhamH1_eq_smul_stepConnecting
    (v : Circle)
    (alpha : DeRhamCohomology (I := AnnularCylinderModel)
      (M := Circle × ℝ) (A := ℝ) 1) :
    ∃ d : ℝ, alpha = d • annularStepConnectingClass v := by
  let U := annularPunctureOpen v
  let V := annularPunctureOpen (annularOpposite v)
  let hcover : U ⊔ V = ⊤ := annularPunctures_cover v
  letI : Subsingleton
      (DeRhamCohomology (I := AnnularCylinderModel) (M := U) (A := ℝ) 1) := by
    simpa [U] using annularPuncture_deRhamH1_subsingleton v
  letI : Subsingleton
      (DeRhamCohomology (I := AnnularCylinderModel) (M := V) (A := ℝ) 1) := by
    simpa [V] using annularPuncture_deRhamH1_subsingleton (annularOpposite v)
  let connecting :=
    deRhamMayerVietorisConnectingOfPartitionOfUnity (A := ℝ)
      AnnularCylinderModel U V hcover 0
  have hrestriction :
      deRhamMayerVietorisRestriction (I := AnnularCylinderModel) (A := ℝ)
          U V 1 alpha = 0 := by
    apply Prod.ext
    · exact Subsingleton.elim _ _
    · exact Subsingleton.elim _ _
  have hexact :=
    deRham_mayerVietoris_exact_connecting_restriction_of_partitionOfUnity
      (A := ℝ) AnnularCylinderModel U V hcover 0
  have hrange : alpha ∈ Set.range connecting := (hexact alpha).mp hrestriction
  rcases hrange with ⟨eta, heta⟩
  change DeRhamCohomology (I := AnnularCylinderModel)
    (M := annularDoublePunctureOpen v) (A := ℝ) 0 at eta
  rcases annularDoublePuncture_H0_eq_constant_add_smul_step v eta with
    ⟨c, d, hdecomp⟩
  have hconstant_range :
      deRhamConstantH0Class (I0 := AnnularCylinderModel)
          (M0 := annularDoublePunctureOpen v) c ∈
        Set.range
          (deRhamMayerVietorisDifference (I := AnnularCylinderModel) (A := ℝ)
            U V 0) := by
    refine ⟨
      (deRhamConstantH0Class (I0 := AnnularCylinderModel) (M0 := U) c,
        0), ?_⟩
    change
      deRhamCohomologyRestrictionOfLE (I := AnnularCylinderModel) (A := ℝ)
          (W := annularDoublePunctureOpen v) (V := U) inf_le_left 0
          (deRhamConstantH0Class (I0 := AnnularCylinderModel) (M0 := U) c) -
        deRhamCohomologyRestrictionOfLE (I := AnnularCylinderModel) (A := ℝ)
          (W := annularDoublePunctureOpen v) (V := V) inf_le_right 0 0 =
        deRhamConstantH0Class (I0 := AnnularCylinderModel)
          (M0 := annularDoublePunctureOpen v) c
    rw [deRhamCohomologyRestrictionOfLE_constant]
    simp
  have hconstant_zero :
      connecting
          (deRhamConstantH0Class (I0 := AnnularCylinderModel)
            (M0 := annularDoublePunctureOpen v) c) = 0 := by
    have hexact0 :=
      deRham_mayerVietoris_exact_difference_connecting_of_partitionOfUnity
        (A := ℝ) AnnularCylinderModel U V hcover 0
    exact (hexact0 _).mpr hconstant_range
  refine ⟨d, ?_⟩
  calc
    alpha = connecting eta := heta.symm
    _ = connecting
        (deRhamConstantH0Class (I0 := AnnularCylinderModel)
            (M0 := annularDoublePunctureOpen v) c +
          d • annularOverlapStepClass v) := congrArg connecting hdecomp
    _ = connecting
          (deRhamConstantH0Class (I0 := AnnularCylinderModel)
            (M0 := annularDoublePunctureOpen v) c) +
        connecting (d • annularOverlapStepClass v) :=
      deRhamMayerVietorisConnectingOfPartitionOfUnity_add
        AnnularCylinderModel U V hcover 0 _ _
    _ = 0 + d • connecting (annularOverlapStepClass v) := by
      have hsmul :=
        deRhamMayerVietorisConnectingOfPartitionOfUnity_smul
          AnnularCylinderModel U V hcover 0 d (annularOverlapStepClass v)
      change connecting (d • annularOverlapStepClass v) =
        d • connecting (annularOverlapStepClass v) at hsmul
      rw [hconstant_zero, hsmul]
    _ = d • annularStepConnectingClass v := by
      simp [annularStepConnectingClass, U, V, connecting]

set_option synthInstance.maxHeartbeats 100000 in
set_option maxHeartbeats 800000 in
/--
%%handwave
name:
  Nonvanishing of the annular connecting class
statement:
  The Mayer--Vietoris connecting class of the overlap step function is
  nonzero in \(H_{\mathrm{dR}}^1(S^1\times\mathbb R;\mathbb R)\).
proof:
  If it vanished, exactness would express the overlap step as the difference
  of two constant degree-zero classes on the singly punctured cylinders.
  Restriction to the positive component would force their difference to be
  \(1\), while restriction to the negative component would force it to be
  \(0\), a contradiction.
-/
theorem annularStepConnectingClass_ne_zero (v : Circle) :
    annularStepConnectingClass v ≠ 0 := by
  intro hzero
  let U := annularPunctureOpen v
  let V := annularPunctureOpen (annularOpposite v)
  let hcover : U ⊔ V = ⊤ := annularPunctures_cover v
  let connecting :=
    deRhamMayerVietorisConnectingOfPartitionOfUnity (A := ℝ)
      AnnularCylinderModel U V hcover 0
  have hzero' : connecting (annularOverlapStepClass v) = 0 := by
    simpa [annularStepConnectingClass, U, V, connecting] using hzero
  have hexact :=
    deRham_mayerVietoris_exact_difference_connecting_of_partitionOfUnity
      (A := ℝ) AnnularCylinderModel U V hcover 0
  have hrange : annularOverlapStepClass v ∈
      Set.range
        (deRhamMayerVietorisDifference (I := AnnularCylinderModel) (A := ℝ)
          U V 0) := (hexact _).mp hzero'
  rcases hrange with ⟨⟨alpha, beta⟩, hab⟩
  rcases annularPuncture_H0_eq_constant v alpha with ⟨c, hc⟩
  rcases annularPuncture_H0_eq_constant (annularOpposite v) beta with ⟨d, hd⟩
  rw [hc, hd] at hab
  change
    deRhamCohomologyRestrictionOfLE (I := AnnularCylinderModel) (A := ℝ)
        (W := annularDoublePunctureOpen v) (V := U) inf_le_left 0
        (deRhamConstantH0Class (I0 := AnnularCylinderModel) (M0 := U) c) -
      deRhamCohomologyRestrictionOfLE (I := AnnularCylinderModel) (A := ℝ)
        (W := annularDoublePunctureOpen v) (V := V) inf_le_right 0
        (deRhamConstantH0Class (I0 := AnnularCylinderModel) (M0 := V) d) =
      annularOverlapStepClass v at hab
  rw [deRhamCohomologyRestrictionOfLE_constant,
    deRhamCohomologyRestrictionOfLE_constant,
    deRhamConstantH0Class_sub] at hab
  have hpositive := congrArg
    (deRhamCohomologyRestrictionOfLE (I := AnnularCylinderModel) (A := ℝ)
      (annularPositiveComponent_le_doublePuncture v) 0) hab
  have hnegative := congrArg
    (deRhamCohomologyRestrictionOfLE (I := AnnularCylinderModel) (A := ℝ)
      (annularNegativeComponent_le_doublePuncture v) 0) hab
  rw [deRhamCohomologyRestrictionOfLE_constant,
    annularOverlapStepClass_restrict_positive] at hpositive
  rw [deRhamCohomologyRestrictionOfLE_constant,
    annularOverlapStepClass_restrict_negative] at hnegative
  letI : Nonempty (annularPositiveComponent v) :=
    annularPositiveComponent_nonempty v
  letI : Nonempty (annularNegativeComponent v) :=
    annularNegativeComponent_nonempty v
  have hcd_one : c - d = 1 :=
    deRhamConstantH0Class_injective hpositive
  have hcd_zero : c - d = 0 :=
    deRhamConstantH0Class_injective hnegative
  linarith

set_option synthInstance.maxHeartbeats 100000 in
set_option maxHeartbeats 800000 in
/--
%%handwave
name:
  Every nonzero annular first cohomology class is a generator
statement:
  If \(0\ne\tau\in H_{\mathrm{dR}}^1(S^1\times\mathbb R;\mathbb R)\), then
  every \(\alpha\) is of the form \(\alpha=c\tau\) for some
  \(c\in\mathbb R\).
proof:
  Both \(\tau\) and \(\alpha\) are multiples of the nonzero connecting step
  class.  The coefficient of \(\tau\) is nonzero, so divide the coefficient
  of \(\alpha\) by it.
-/
theorem annularCylinder_deRhamH1_eq_smul_of_ne_zero
    (v : Circle)
    (tau : DeRhamCohomology (I := AnnularCylinderModel)
      (M := Circle × ℝ) (A := ℝ) 1)
    (htau : tau ≠ 0)
    (alpha : DeRhamCohomology (I := AnnularCylinderModel)
      (M := Circle × ℝ) (A := ℝ) 1) :
    ∃ c : ℝ, alpha = c • tau := by
  rcases annularCylinder_deRhamH1_eq_smul_stepConnecting v tau with
    ⟨d, hd⟩
  have hd_ne : d ≠ 0 := by
    intro hd_zero
    apply htau
    simpa [hd_zero] using hd
  rcases annularCylinder_deRhamH1_eq_smul_stepConnecting v alpha with
    ⟨e, he⟩
  refine ⟨e / d, ?_⟩
  rw [he, hd]
  rw [smul_smul]
  field_simp

/--
%%handwave
name:
  Every nonzero first cohomology class of a smooth annulus is a generator
statement:
  Let \(M\) be diffeomorphic to \(S^1\times\mathbb R\).  If
  \(0\ne\tau\in H_{\mathrm{dR}}^1(M;\mathbb R)\), then every class
  \(\alpha\) equals \(c\tau\) for some \(c\in\mathbb R\).
proof:
  Transport both classes to the standard annular cylinder, use that any
  nonzero class generates its one-dimensional first cohomology, and pull the
  resulting scalar relation back.
-/
theorem deRhamH1_eq_smul_of_diffeomorphic_annularCylinder
    {E H M : Type*}
    [NormedAddCommGroup E] [NormedSpace ℝ E]
    [TopologicalSpace H] [TopologicalSpace M] [ChartedSpace H M]
    (I : ModelWithCorners ℝ E H) [IsManifold I ∞ M]
    (phi : M ≃ₘ⟮I, AnnularCylinderModel⟯ Circle × ℝ)
    (v : Circle)
    (tau : DeRhamCohomology (I := I) (M := M) (A := ℝ) 1)
    (htau : tau ≠ 0)
    (alpha : DeRhamCohomology (I := I) (M := M) (A := ℝ) 1) :
    ∃ c : ℝ, alpha = c • tau := by
  let tauCylinder := deRhamCohomologyPullbackDiffeomorph
    AnnularCylinderModel I phi.symm 1 tau
  have htauCylinder : tauCylinder ≠ 0 := by
    intro htauCylinder_zero
    apply htau
    calc
      tau = deRhamCohomologyPullbackDiffeomorph
          I AnnularCylinderModel phi 1 tauCylinder :=
        (deRhamCohomologyPullbackDiffeomorph_comp_symm
          I AnnularCylinderModel phi 1 tau).symm
      _ = 0 := by
        rw [htauCylinder_zero]
        exact (deRhamCohomologyPullbackDiffeomorph
          I AnnularCylinderModel phi 1).map_zero
  let alphaCylinder := deRhamCohomologyPullbackDiffeomorph
    AnnularCylinderModel I phi.symm 1 alpha
  rcases annularCylinder_deRhamH1_eq_smul_of_ne_zero
      v tauCylinder htauCylinder alphaCylinder with ⟨c, hc⟩
  refine ⟨c, ?_⟩
  calc
    alpha = deRhamCohomologyPullbackDiffeomorph
        I AnnularCylinderModel phi 1 alphaCylinder :=
      (deRhamCohomologyPullbackDiffeomorph_comp_symm
        I AnnularCylinderModel phi 1 alpha).symm
    _ = deRhamCohomologyPullbackDiffeomorph
        I AnnularCylinderModel phi 1 (c • tauCylinder) := congrArg _ hc
    _ = c • deRhamCohomologyPullbackDiffeomorph
        I AnnularCylinderModel phi 1 tauCylinder := by rw [map_smul]
    _ = c • tau := by
      rw [deRhamCohomologyPullbackDiffeomorph_comp_symm]

set_option synthInstance.maxHeartbeats 100000 in
set_option maxHeartbeats 800000 in
/--
%%handwave
name:
  Equality of annular de Rham classes from one nonzero period
statement:
  Let \(\alpha,\tau\) be closed one-forms on a smooth annulus and \(c\) a
  one-cycle.  If
  \[
    \int_c\alpha=\int_c\tau\ne0,
  \]
  then \([\alpha]=[\tau]\) in first de Rham cohomology.
proof:
  Since \([\tau]\ne0\), it generates annular first cohomology, so
  \([\alpha]=a[\tau]\).  The form \(\alpha-a\tau\) is exact and has zero
  period on \(c\); the displayed equality and nonzero period force \(a=1\).
-/
theorem deRhamH1_class_eq_of_annular_eq_period
    {E H M : Type*}
    [NormedAddCommGroup E] [NormedSpace ℝ E]
    [TopologicalSpace H] [TopologicalSpace M] [ChartedSpace H M]
    (I : ModelWithCorners ℝ E H) [IsManifold I ∞ M]
    (phi : M ≃ₘ⟮I, AnnularCylinderModel⟯ Circle × ℝ)
    (v : Circle)
    (alpha tau : DeRhamClosedForms (I := I) (M := M) (A := ℝ) 1)
    (c : SingularChain (I := I) (M := M) 1 ∞)
    (hcycle : boundary (I := I) c = 0)
    (hperiod :
      integrateSmoothChain (I := I)
          (alpha : SmoothForms (I := I) (M := M) ℝ 1) c =
        integrateSmoothChain (I := I)
          (tau : SmoothForms (I := I) (M := M) ℝ 1) c)
    (htauPeriod :
      integrateSmoothChain (I := I)
        (tau : SmoothForms (I := I) (M := M) ℝ 1) c ≠ 0) :
    (DeRhamExactClosedForms (I := I) (M := M) (A := ℝ) 1).mkQ alpha =
      (DeRhamExactClosedForms (I := I) (M := M) (A := ℝ) 1).mkQ tau := by
  let alphaClass :=
    (DeRhamExactClosedForms (I := I) (M := M) (A := ℝ) 1).mkQ alpha
  let tauClass :=
    (DeRhamExactClosedForms (I := I) (M := M) (A := ℝ) 1).mkQ tau
  have htauClass : tauClass ≠ 0 :=
    deRhamCohomologyClass_ne_zero_of_nonzero_period
      (I := I) tau c hcycle htauPeriod
  rcases deRhamH1_eq_smul_of_diffeomorphic_annularCylinder
      I phi v tauClass htauClass alphaClass with ⟨a, ha⟩
  have hdiffClass :
      (DeRhamExactClosedForms (I := I) (M := M) (A := ℝ) 1).mkQ
          (alpha - a • tau) = 0 := by
    rw [map_sub, map_smul]
    change alphaClass - a • tauClass = 0
    rw [ha, sub_self]
  have hmem :
      (alpha - a • tau : DeRhamClosedForms
        (I := I) (M := M) (A := ℝ) 1) ∈
        DeRhamExactClosedForms (I := I) (M := M) (A := ℝ) 1 := by
    rw [← Submodule.Quotient.mk_eq_zero]
    simpa [Submodule.mkQ_apply] using hdiffClass
  have hexact :
      ((alpha - a • tau : DeRhamClosedForms
          (I := I) (M := M) (A := ℝ) 1) :
        SmoothForms (I := I) (M := M) ℝ 1) ∈
        DeRhamExactForms (I := I) (M := M) (A := ℝ) 1 := by
    simpa [DeRhamExactClosedForms] using hmem
  have hzero := integrateSmoothChain_eq_zero_of_mem_deRhamExactForms_one
    (I := I)
    (omega := ((alpha - a • tau : DeRhamClosedForms
      (I := I) (M := M) (A := ℝ) 1) :
        SmoothForms (I := I) (M := M) ℝ 1)) hexact c hcycle
  change integrateSmoothChain (I := I)
    ((alpha : SmoothForms (I := I) (M := M) ℝ 1) -
      a • (tau : SmoothForms (I := I) (M := M) ℝ 1)) c = 0 at hzero
  rw [show
      (alpha : SmoothForms (I := I) (M := M) ℝ 1) -
          a • (tau : SmoothForms (I := I) (M := M) ℝ 1) =
        (alpha : SmoothForms (I := I) (M := M) ℝ 1) +
          (-a) • (tau : SmoothForms (I := I) (M := M) ℝ 1) by module,
    integrateSmoothChain_add_form, integrateSmoothChain_smul_form] at hzero
  have ha_one : a = 1 := by
    rw [hperiod] at hzero
    have hfactor :
        (1 - a) * integrateSmoothChain (I := I)
          (tau : SmoothForms (I := I) (M := M) ℝ 1) c = 0 := by
      calc
        _ = integrateSmoothChain (I := I)
              (tau : SmoothForms (I := I) (M := M) ℝ 1) c +
            -a * integrateSmoothChain (I := I)
              (tau : SmoothForms (I := I) (M := M) ℝ 1) c := by ring
        _ = 0 := hzero
    have hone : 1 - a = 0 :=
      (mul_eq_zero.mp hfactor).resolve_right htauPeriod
    linarith
  change alphaClass = tauClass
  rw [ha, ha_one, one_smul]

set_option synthInstance.maxHeartbeats 100000 in
set_option maxHeartbeats 800000 in
/--
%%handwave
name:
  Annular de Rham classes from periods equal up to sign
statement:
  Let \(\alpha,\tau\) be closed one-forms on a smooth annulus and let \(c\)
  be a one-cycle with \(\int_c\tau\ne0\).  If
  \(\int_c\alpha=\int_c\tau\) or
  \(\int_c\alpha=-\int_c\tau\), then respectively
  \([\alpha]=[\tau]\) or \([\alpha]=-[\tau]\).
proof:
  Apply the equality-from-period theorem either to \(\tau\) or to
  \(-\tau\).
-/
theorem deRhamH1_class_eq_or_neg_of_annular_period_eq_or_neg
    {E H M : Type*}
    [NormedAddCommGroup E] [NormedSpace ℝ E]
    [TopologicalSpace H] [TopologicalSpace M] [ChartedSpace H M]
    (I : ModelWithCorners ℝ E H) [IsManifold I ∞ M]
    (phi : M ≃ₘ⟮I, AnnularCylinderModel⟯ Circle × ℝ)
    (v : Circle)
    (alpha tau : DeRhamClosedForms (I := I) (M := M) (A := ℝ) 1)
    (c : SingularChain (I := I) (M := M) 1 ∞)
    (hcycle : boundary (I := I) c = 0)
    (hperiod :
      integrateSmoothChain (I := I)
          (alpha : SmoothForms (I := I) (M := M) ℝ 1) c =
          integrateSmoothChain (I := I)
            (tau : SmoothForms (I := I) (M := M) ℝ 1) c ∨
      integrateSmoothChain (I := I)
          (alpha : SmoothForms (I := I) (M := M) ℝ 1) c =
          -integrateSmoothChain (I := I)
            (tau : SmoothForms (I := I) (M := M) ℝ 1) c)
    (htauPeriod :
      integrateSmoothChain (I := I)
        (tau : SmoothForms (I := I) (M := M) ℝ 1) c ≠ 0) :
    (DeRhamExactClosedForms (I := I) (M := M) (A := ℝ) 1).mkQ alpha =
        (DeRhamExactClosedForms (I := I) (M := M) (A := ℝ) 1).mkQ tau ∨
      (DeRhamExactClosedForms (I := I) (M := M) (A := ℝ) 1).mkQ alpha =
        -(DeRhamExactClosedForms (I := I) (M := M) (A := ℝ) 1).mkQ tau := by
  rcases hperiod with hperiod | hperiod
  · exact Or.inl (deRhamH1_class_eq_of_annular_eq_period
      I phi v alpha tau c hcycle hperiod htauPeriod)
  · right
    have hnegPeriod :
        integrateSmoothChain (I := I)
            (alpha : SmoothForms (I := I) (M := M) ℝ 1) c =
          integrateSmoothChain (I := I)
            ((-tau : DeRhamClosedForms
              (I := I) (M := M) (A := ℝ) 1) :
                SmoothForms (I := I) (M := M) ℝ 1) c := by
      rw [show
          ((-tau : DeRhamClosedForms
              (I := I) (M := M) (A := ℝ) 1) :
                SmoothForms (I := I) (M := M) ℝ 1) =
            (-1 : ℝ) •
              (tau : SmoothForms (I := I) (M := M) ℝ 1) by
                change -tau.1 = (-1 : ℝ) • tau.1
                module,
        integrateSmoothChain_smul_form]
      simpa using hperiod
    have hnegPeriod_ne :
        integrateSmoothChain (I := I)
          ((-tau : DeRhamClosedForms
            (I := I) (M := M) (A := ℝ) 1) :
              SmoothForms (I := I) (M := M) ℝ 1) c ≠ 0 := by
      rw [show
          ((-tau : DeRhamClosedForms
              (I := I) (M := M) (A := ℝ) 1) :
                SmoothForms (I := I) (M := M) ℝ 1) =
            (-1 : ℝ) •
              (tau : SmoothForms (I := I) (M := M) ℝ 1) by
                change -tau.1 = (-1 : ℝ) • tau.1
                module,
        integrateSmoothChain_smul_form]
      simpa using htauPeriod
    have hclass := deRhamH1_class_eq_of_annular_eq_period
      I phi v alpha (-tau) c hcycle hnegPeriod hnegPeriod_ne
    simpa using hclass

/--
%%handwave
name:
  Surjectivity onto annular first cohomology from one nonzero range element
statement:
  Let \(L:X\to H_{\mathrm{dR}}^1(A;\mathbb R)\) be linear, where \(A\) is a
  smooth annulus.  If the range of \(L\) contains a nonzero class \(\tau\),
  then \(L\) is surjective.
proof:
  Every annular first cohomology class is a scalar multiple of \(\tau\), and
  the range of a linear map contains all scalar multiples of each of its
  elements.
-/
theorem deRhamH1_map_surjective_of_annular_nonzero_mem_range
    {E₁ H₁ M₁ E₂ H₂ M₂ : Type*}
    [NormedAddCommGroup E₁] [NormedSpace ℝ E₁]
    [NormedAddCommGroup E₂] [NormedSpace ℝ E₂]
    [TopologicalSpace H₁] [TopologicalSpace M₁] [ChartedSpace H₁ M₁]
    [TopologicalSpace H₂] [TopologicalSpace M₂] [ChartedSpace H₂ M₂]
    (I₁ : ModelWithCorners ℝ E₁ H₁) (I₂ : ModelWithCorners ℝ E₂ H₂)
    [IsManifold I₁ ∞ M₁] [IsManifold I₂ ∞ M₂]
    (phi : M₂ ≃ₘ⟮I₂, AnnularCylinderModel⟯ Circle × ℝ)
    (v : Circle)
    (f : DeRhamCohomology (I := I₁) (M := M₁) (A := ℝ) 1 →ₗ[ℝ]
      DeRhamCohomology (I := I₂) (M := M₂) (A := ℝ) 1)
    (tau : DeRhamCohomology (I := I₂) (M := M₂) (A := ℝ) 1)
    (htau : tau ≠ 0) (htau_range : tau ∈ LinearMap.range f) :
    Function.Surjective f := by
  intro alpha
  rcases deRhamH1_eq_smul_of_diffeomorphic_annularCylinder
      I₂ phi v tau htau alpha with ⟨c, hc⟩
  rcases htau_range with ⟨beta, hbeta⟩
  refine ⟨c • beta, ?_⟩
  rw [map_smul, hbeta, ← hc]

/--
%%handwave
name:
  Surjectivity of restriction to an annulus from a nonzero period
statement:
  Let \(W\subseteq V\) be open with \(W\) a smooth annulus.  If a closed
  one-form on \(V\) restricts to a form having nonzero period on a cycle in
  \(W\), then
  \[
    H_{\mathrm{dR}}^1(V;\mathbb R)\longrightarrow
    H_{\mathrm{dR}}^1(W;\mathbb R)
  \]
  is surjective.
proof:
  The period criterion shows that the restricted class is nonzero.  It lies
  in the range of restriction and, as a nonzero annular class, generates the
  entire target.
-/
theorem deRhamCohomologyRestrictionOfLE_surjective_of_annular_nonzero_period
    {E H M : Type*}
    [NormedAddCommGroup E] [NormedSpace ℝ E]
    [TopologicalSpace H] [TopologicalSpace M] [ChartedSpace H M]
    (I : ModelWithCorners ℝ E H) [IsManifold I ∞ M]
    {W V : TopologicalSpace.Opens M} (hWV : W ≤ V)
    (phi : W ≃ₘ⟮I, AnnularCylinderModel⟯ Circle × ℝ)
    (v : Circle)
    (omega : DeRhamClosedForms (I := I) (M := V) (A := ℝ) 1)
    (c : SingularChain (I := I) (M := W) 1 ∞)
    (hcycle : boundary (I := I) c = 0)
    (hperiod :
      integrateSmoothChain (I := I)
        (restrictSmoothFormsOfLE (I := I) (A := ℝ) hWV 1
          (omega : SmoothForms (I := I) (M := V) ℝ 1)) c ≠ 0) :
    Function.Surjective
      (deRhamCohomologyRestrictionOfLE (I := I) (A := ℝ) hWV 1) := by
  let beta :=
    (DeRhamExactClosedForms (I := I) (M := V) (A := ℝ) 1).mkQ omega
  let tau := deRhamCohomologyRestrictionOfLE
    (I := I) (A := ℝ) hWV 1 beta
  have htau : tau ≠ 0 := by
    exact deRhamCohomologyRestrictionOfLE_ne_zero_of_nonzero_period
      (I := I) hWV omega c hcycle hperiod
  apply deRhamH1_map_surjective_of_annular_nonzero_mem_range
    I I phi v
    (deRhamCohomologyRestrictionOfLE (I := I) (A := ℝ) hWV 1)
    tau htau
  exact ⟨beta, rfl⟩

set_option synthInstance.maxHeartbeats 100000 in
set_option maxHeartbeats 800000 in
/--
%%handwave
name:
  Injectivity of one restriction in a two-open cover
statement:
  Let \(M=U\cup V\).  If
  \(H_{\mathrm{dR}}^1(M;\mathbb R)=0\) and
  \(H_{\mathrm{dR}}^1(V;\mathbb R)=0\), then restriction
  \[
    H_{\mathrm{dR}}^1(U;\mathbb R)\longrightarrow
    H_{\mathrm{dR}}^1(U\cap V;\mathbb R)
  \]
  is injective.
proof:
  If two classes have the same restriction, their difference paired with zero
  on \(V\) lies in the kernel of the Mayer--Vietoris difference map.
  Exactness lifts this pair from an ambient class, which is zero; hence the
  difference on \(U\) is zero.
-/
theorem deRhamH1_left_restriction_injective_of_ambient_right_subsingleton
    {E H M : Type*}
    [NormedAddCommGroup E] [NormedSpace ℝ E] [FiniteDimensional ℝ E]
    [TopologicalSpace H] [TopologicalSpace M] [ChartedSpace H M]
    (I : ModelWithCorners ℝ E H) [IsManifold I ∞ M]
    [T2Space M] [SigmaCompactSpace M]
    [Subsingleton
      (DeRhamCohomology (I := I) (M := M) (A := ℝ) 1)]
    (U V : TopologicalSpace.Opens M) (hcover : U ⊔ V = ⊤)
    [Subsingleton
      (DeRhamCohomology (I := I) (M := V) (A := ℝ) 1)] :
    Function.Injective
      (deRhamCohomologyRestrictionOfLE (I := I) (A := ℝ)
        (W := (U ⊓ V : TopologicalSpace.Opens M)) (V := U)
        inf_le_left 1) := by
  intro alpha beta hab
  let rho := deRhamCohomologyRestrictionOfLE
    (I := I) (A := ℝ)
    (W := (U ⊓ V : TopologicalSpace.Opens M)) (V := U)
    inf_le_left 1
  let sigma := deRhamCohomologyRestrictionOfLE
    (I := I) (A := ℝ)
    (W := (U ⊓ V : TopologicalSpace.Opens M)) (V := V)
    inf_le_right 1
  let delta := alpha - beta
  have hrho_delta : rho delta = 0 := by
    change (deRhamCohomologyRestrictionOfLE (I := I) (A := ℝ)
      (W := (U ⊓ V : TopologicalSpace.Opens M)) (V := U)
      inf_le_left 1) (alpha - beta) = 0
    rw [(deRhamCohomologyRestrictionOfLE (I := I) (A := ℝ)
      (W := (U ⊓ V : TopologicalSpace.Opens M)) (V := U)
      inf_le_left 1).map_sub, hab, sub_self]
  let zeroV : DeRhamCohomology (I := I) (M := V) (A := ℝ) 1 := 0
  have hdiff :
      deRhamMayerVietorisDifference (I := I) (A := ℝ) U V 1
          (delta, zeroV) = 0 := by
    change rho delta - sigma zeroV = 0
    rw [hrho_delta]
    have hsigma_zero : sigma zeroV = 0 := by
      exact sigma.map_zero
    rw [hsigma_zero, sub_zero]
  rcases deRham_mayerVietoris_longExact (A := ℝ) I U V hcover with ⟨LES⟩
  rcases (LES.exact_restriction_difference 1 (delta, zeroV)).mp hdiff with
    ⟨ambient, hambient⟩
  have hambient_zero : ambient = 0 := Subsingleton.elim _ _
  have hpair : (delta, zeroV) =
      (0 : DeRhamCohomology (I := I) (M := U) (A := ℝ) 1 ×
        DeRhamCohomology (I := I) (M := V) (A := ℝ) 1) := by
    calc
      (delta, zeroV) = deRhamMayerVietorisRestriction
          (I := I) (A := ℝ) U V 1 ambient := hambient.symm
      _ = deRhamMayerVietorisRestriction
          (I := I) (A := ℝ) U V 1 0 := congrArg _ hambient_zero
      _ = 0 := by
        apply Prod.ext
        · exact (deRhamCohomologyRestrictionToOpen
            (I := I) (M := M) (A := ℝ) U 1).map_zero
        · exact (deRhamCohomologyRestrictionToOpen
            (I := I) (M := M) (A := ℝ) V 1).map_zero
  have hdelta : delta = 0 := congrArg Prod.fst hpair
  exact sub_eq_zero.mp hdelta


set_option synthInstance.maxHeartbeats 100000 in
/--
%%handwave
name:
  Mayer--Vietoris vanishing across an annular overlap
statement:
  Let \(M=U\cup V\), suppose \(U\cap V\) is a smooth annulus and
  \(H_{\mathrm{dR}}^1(M;\mathbb R)=0\).  If
  \(H_{\mathrm{dR}}^1(U;\mathbb R)\ne0\), then
  \(H_{\mathrm{dR}}^1(V;\mathbb R)=0\).
proof:
  Choose a nonzero class on \(U\).  Exactness and ambient vanishing show that
  its restriction to \(U\cap V\) is nonzero.  Since any nonzero annular class
  generates the overlap cohomology, the left restriction is surjective.
  The Mayer--Vietoris injectivity criterion then forces the right first
  cohomology to vanish.
-/
theorem deRhamH1_subsingleton_of_mayerVietoris_annular_and_left_nontrivial
    {E H M : Type*}
    [NormedAddCommGroup E] [NormedSpace ℝ E] [FiniteDimensional ℝ E]
    [TopologicalSpace H] [TopologicalSpace M] [ChartedSpace H M]
    (I : ModelWithCorners ℝ E H) [IsManifold I ∞ M]
    [T2Space M] [SigmaCompactSpace M]
    [Subsingleton
      (DeRhamCohomology (I := I) (M := M) (A := ℝ) 1)]
    (U V : TopologicalSpace.Opens M) (hcover : U ⊔ V = ⊤)
    (phi : (U ⊓ V : TopologicalSpace.Opens M) ≃ₘ⟮I,
      AnnularCylinderModel⟯ Circle × ℝ)
    (v : Circle)
    (hleft : ¬ Subsingleton
      (DeRhamCohomology (I := I) (M := U) (A := ℝ) 1)) :
    Subsingleton
      (DeRhamCohomology (I := I) (M := V) (A := ℝ) 1) := by
  letI : Nontrivial
      (DeRhamCohomology (I := I) (M := U) (A := ℝ) 1) :=
    not_subsingleton_iff_nontrivial.mp hleft
  rcases exists_ne
      (0 : DeRhamCohomology (I := I) (M := U) (A := ℝ) 1) with
    ⟨tau, htau⟩
  let rho := deRhamCohomologyRestrictionOfLE
    (I := I) (A := ℝ)
    (W := (U ⊓ V : TopologicalSpace.Opens M)) (V := U)
    inf_le_left 1
  have hrho_tau : rho tau ≠ 0 := by
    intro hrho_tau_zero
    rcases deRham_mayerVietoris_longExact (A := ℝ) I U V hcover with ⟨LES⟩
    let zeroV : DeRhamCohomology (I := I) (M := V) (A := ℝ) 1 := 0
    have hdiff :
        deRhamMayerVietorisDifference (I := I) (A := ℝ) U V 1
            (tau, zeroV) = 0 := by
      change rho tau -
        deRhamCohomologyRestrictionOfLE (I := I) (A := ℝ)
          (W := (U ⊓ V : TopologicalSpace.Opens M)) (V := V)
          inf_le_right 1 0 = 0
      rw [hrho_tau_zero]
      rw [(deRhamCohomologyRestrictionOfLE (I := I) (A := ℝ)
        (W := (U ⊓ V : TopologicalSpace.Opens M)) (V := V)
        inf_le_right 1).map_zero]
      exact sub_self
        (0 : DeRhamCohomology (I := I)
          (M := (U ⊓ V : TopologicalSpace.Opens M)) (A := ℝ) 1)
    rcases (LES.exact_restriction_difference 1 (tau, zeroV)).mp hdiff with
      ⟨ambient, hambient⟩
    have hambient_zero : ambient = 0 := Subsingleton.elim _ _
    have hpair : (tau, zeroV) =
        (0 : DeRhamCohomology (I := I) (M := U) (A := ℝ) 1 ×
          DeRhamCohomology (I := I) (M := V) (A := ℝ) 1) := by
      calc
        (tau, 0) = deRhamMayerVietorisRestriction
            (I := I) (A := ℝ) U V 1 ambient := hambient.symm
        _ = deRhamMayerVietorisRestriction
            (I := I) (A := ℝ) U V 1 0 := congrArg _ hambient_zero
        _ = 0 := by
          apply Prod.ext
          · exact (deRhamCohomologyRestrictionToOpen
              (I := I) (M := M) (A := ℝ) U 1).map_zero
          · exact (deRhamCohomologyRestrictionToOpen
              (I := I) (M := M) (A := ℝ) V 1).map_zero
    exact htau (congrArg Prod.fst hpair)
  apply deRhamH1_subsingleton_of_mayerVietoris_left_restriction_surjective
    (A := ℝ) I U V hcover
  intro alpha
  rcases deRhamH1_eq_smul_of_diffeomorphic_annularCylinder
      I phi v (rho tau) hrho_tau alpha with ⟨c, hc⟩
  refine ⟨c • tau, ?_⟩
  rw [map_smul, ← hc]

end
end JJMath.Manifold
