import JJMath.Manifold.DeRhamMayerVietorisLinear

/-!
# First de Rham cohomology from a two-open circular cover

This file isolates the algebraic part of the annulus calculation.  If two
open sets have trivial first cohomology and their overlap has degree-zero
cohomology generated by a constant class and one step class, the connecting
class of that step generates first cohomology of the union.
-/

open Set
open scoped Manifold ContDiff Topology

namespace JJMath.Manifold

noncomputable section

universe v w m

variable {E : Type v} [NormedAddCommGroup E] [NormedSpace ℝ E]
variable {H : Type w} [TopologicalSpace H]
variable {M : Type m} [TopologicalSpace M] [ChartedSpace H M]

set_option synthInstance.maxHeartbeats 100000 in
/--
%%handwave
name:
  Vanishing on one side of a two-open cyclic cover
statement:
  Let \(M=U\cup V\) with \(H^1_{\mathrm{dR}}(M)=0\).  If
  \(H^1_{\mathrm{dR}}(U\cap V)\) is cyclic and
  \(H^1_{\mathrm{dR}}(U)\ne0\), then
  \(H^1_{\mathrm{dR}}(V)=0\).
proof:
  By Mayer–Vietoris exactness, a nonzero class on \(U\) restricts nontrivially
  to the overlap.  Since the overlap cohomology is cyclic, this nonzero
  restriction spans it, making restriction from \(U\) surjective.  Exactness
  and ambient vanishing then force every class on \(V\) to vanish.
-/
theorem deRhamH1_subsingleton_of_mayerVietoris_cyclic_overlap_and_left_nontrivial
    (I : ModelWithCorners ℝ E H) [IsManifold I ∞ M]
    [FiniteDimensional ℝ E] [T2Space M] [SigmaCompactSpace M]
    [Subsingleton
      (DeRhamCohomology (I := I) (M := M) (A := ℝ) 1)]
    (U V : TopologicalSpace.Opens M) (hcover : U ⊔ V = ⊤)
    (generator : DeRhamCohomology
      (I := I) (M := (U ⊓ V : TopologicalSpace.Opens M)) (A := ℝ) 1)
    (hcyclic : ∀ alpha : DeRhamCohomology
        (I := I) (M := (U ⊓ V : TopologicalSpace.Opens M)) (A := ℝ) 1,
      ∃ c : ℝ, alpha = c • generator)
    (hleft : ¬ Subsingleton
      (DeRhamCohomology (I := I) (M := U) (A := ℝ) 1)) :
    Subsingleton (DeRhamCohomology (I := I) (M := V) (A := ℝ) 1) := by
  letI : Nontrivial
      (DeRhamCohomology (I := I) (M := U) (A := ℝ) 1) :=
    not_subsingleton_iff_nontrivial.mp hleft
  rcases exists_ne
      (0 : DeRhamCohomology (I := I) (M := U) (A := ℝ) 1) with
    ⟨tau, htau⟩
  let rho := deRhamCohomologyRestrictionOfLE
    (I := I) (A := ℝ)
    (W := (U ⊓ V : TopologicalSpace.Opens M)) (V := U)
    inf_le_left 1
  have hrho_tau : rho tau ≠ 0 := by
    intro hrho_tau_zero
    rcases deRham_mayerVietoris_longExact (A := ℝ) I U V hcover with ⟨LES⟩
    let zeroV : DeRhamCohomology (I := I) (M := V) (A := ℝ) 1 := 0
    have hdiff :
        deRhamMayerVietorisDifference (I := I) (A := ℝ) U V 1
            (tau, zeroV) = 0 := by
      change rho tau -
        deRhamCohomologyRestrictionOfLE (I := I) (A := ℝ)
          (W := (U ⊓ V : TopologicalSpace.Opens M)) (V := V)
          inf_le_right 1 0 = 0
      rw [hrho_tau_zero]
      rw [(deRhamCohomologyRestrictionOfLE (I := I) (A := ℝ)
        (W := (U ⊓ V : TopologicalSpace.Opens M)) (V := V)
        inf_le_right 1).map_zero]
      exact sub_self
        (0 : DeRhamCohomology (I := I)
          (M := (U ⊓ V : TopologicalSpace.Opens M)) (A := ℝ) 1)
    rcases (LES.exact_restriction_difference 1 (tau, zeroV)).mp hdiff with
      ⟨ambient, hambient⟩
    have hambient_zero : ambient = 0 := Subsingleton.elim _ _
    have hpair : (tau, zeroV) =
        (0 : DeRhamCohomology (I := I) (M := U) (A := ℝ) 1 ×
          DeRhamCohomology (I := I) (M := V) (A := ℝ) 1) := by
      calc
        (tau, 0) = deRhamMayerVietorisRestriction
            (I := I) (A := ℝ) U V 1 ambient := hambient.symm
        _ = deRhamMayerVietorisRestriction
            (I := I) (A := ℝ) U V 1 0 := congrArg _ hambient_zero
        _ = 0 := by
          apply Prod.ext
          · exact (deRhamCohomologyRestrictionToOpen
              (I := I) (M := M) (A := ℝ) U 1).map_zero
          · exact (deRhamCohomologyRestrictionToOpen
              (I := I) (M := M) (A := ℝ) V 1).map_zero
    exact htau (congrArg Prod.fst hpair)
  rcases hcyclic (rho tau) with ⟨c, hc⟩
  have hc_ne : c ≠ 0 := by
    intro hc_zero
    apply hrho_tau
    rw [hc, hc_zero, zero_smul]
  apply deRhamH1_subsingleton_of_mayerVietoris_left_restriction_surjective
    (A := ℝ) I U V hcover
  intro alpha
  rcases hcyclic alpha with ⟨d, hd⟩
  refine ⟨(d * c⁻¹) • tau, ?_⟩
  rw [map_smul, hc, smul_smul]
  simpa [hc_ne] using hd.symm

set_option synthInstance.maxHeartbeats 100000 in
set_option synthInstance.maxHeartbeats 100000 in
set_option maxHeartbeats 800000 in
set_option synthInstance.maxHeartbeats 100000 in
set_option maxHeartbeats 800000 in
end

end JJMath.Manifold
