import JJMath.Manifold.DeRhamMayerVietorisLinear

/-!
# First de Rham cohomology from a two-open circular cover

This file isolates the algebraic part of the annulus calculation.  If two
open sets have trivial first cohomology and their overlap has degree-zero
cohomology generated by a constant class and one step class, the connecting
class of that step generates first cohomology of the union.
-/

open Set
open scoped Manifold ContDiff Topology

namespace JJMath.Manifold

noncomputable section

universe v w m

variable {E : Type v} [NormedAddCommGroup E] [NormedSpace ℝ E]
variable {H : Type w} [TopologicalSpace H]
variable {M : Type m} [TopologicalSpace M] [ChartedSpace H M]

/-- A restriction in first de Rham cohomology is surjective if its target is
spanned by one class which itself extends across the larger open set. -/
theorem deRhamH1_restriction_surjective_of_cyclic_generator_extends
    (I : ModelWithCorners ℝ E H) [IsManifold I ∞ M]
    (U W : TopologicalSpace.Opens M) (hWU : W ≤ U)
    (generator : DeRhamCohomology (I := I) (M := W) (A := ℝ) 1)
    (extension : DeRhamCohomology (I := I) (M := U) (A := ℝ) 1)
    (hextension :
      deRhamCohomologyRestrictionOfLE (I := I) (A := ℝ) hWU 1 extension =
        generator)
    (hcyclic : ∀ alpha : DeRhamCohomology
        (I := I) (M := W) (A := ℝ) 1,
      ∃ c : ℝ, alpha = c • generator) :
    Function.Surjective
      (deRhamCohomologyRestrictionOfLE (I := I) (A := ℝ) hWU 1) := by
  intro alpha
  rcases hcyclic alpha with ⟨c, rfl⟩
  refine ⟨c • extension, ?_⟩
  rw [map_smul, hextension]

/--
%%handwave
name:
  Vanishing from an extendable cyclic overlap class
statement:
  Let \(M=U\cup V\) with \(H^1_{\mathrm{dR}}(M)=0\).  Suppose
  \(H^1_{\mathrm{dR}}(U\cap V)\) is generated over \(\mathbb R\) by
  \(\gamma\), and \(\gamma\) is the restriction of a class on \(U\).  Then
  \(H^1_{\mathrm{dR}}(V)=0\).
proof:
  Every overlap class is a scalar multiple of \(\gamma\), so restriction from
  \(U\) to \(U\cap V\) is surjective.  Mayer--Vietoris exactness and
  \(H^1_{\mathrm{dR}}(M)=0\) then force every class on \(V\) to vanish.
-/
theorem deRhamH1_subsingleton_of_mayerVietoris_cyclic_overlap_generator_extends_left
    (I : ModelWithCorners ℝ E H) [IsManifold I ∞ M]
    [FiniteDimensional ℝ E] [T2Space M] [SigmaCompactSpace M]
    [Subsingleton
      (DeRhamCohomology (I := I) (M := M) (A := ℝ) 1)]
    (U V : TopologicalSpace.Opens M) (hcover : U ⊔ V = ⊤)
    (generator : DeRhamCohomology
      (I := I) (M := (U ⊓ V : TopologicalSpace.Opens M)) (A := ℝ) 1)
    (extension : DeRhamCohomology (I := I) (M := U) (A := ℝ) 1)
    (hextension :
      deRhamCohomologyRestrictionOfLE (I := I) (A := ℝ)
          (W := (U ⊓ V : TopologicalSpace.Opens M)) (V := U)
          inf_le_left 1 extension = generator)
    (hcyclic : ∀ alpha : DeRhamCohomology
        (I := I) (M := (U ⊓ V : TopologicalSpace.Opens M)) (A := ℝ) 1,
      ∃ c : ℝ, alpha = c • generator) :
    Subsingleton (DeRhamCohomology (I := I) (M := V) (A := ℝ) 1) := by
  apply deRhamH1_subsingleton_of_mayerVietoris_left_restriction_surjective
    (A := ℝ) I U V hcover
  exact deRhamH1_restriction_surjective_of_cyclic_generator_extends
    I U (U ⊓ V : TopologicalSpace.Opens M) inf_le_left
      generator extension hextension hcyclic

set_option synthInstance.maxHeartbeats 100000 in
/-- If the first cohomology of a Mayer--Vietoris overlap is cyclic and the
left-hand open set has nontrivial first cohomology, ambient vanishing forces
first cohomology of the right-hand open set to vanish.  Exactness first shows
that every nonzero left-hand class restricts nontrivially.  Its restriction is
therefore a nonzero element of the cyclic overlap and hence spans the overlap,
so the left restriction is surjective. -/
theorem deRhamH1_subsingleton_of_mayerVietoris_cyclic_overlap_and_left_nontrivial
    (I : ModelWithCorners ℝ E H) [IsManifold I ∞ M]
    [FiniteDimensional ℝ E] [T2Space M] [SigmaCompactSpace M]
    [Subsingleton
      (DeRhamCohomology (I := I) (M := M) (A := ℝ) 1)]
    (U V : TopologicalSpace.Opens M) (hcover : U ⊔ V = ⊤)
    (generator : DeRhamCohomology
      (I := I) (M := (U ⊓ V : TopologicalSpace.Opens M)) (A := ℝ) 1)
    (hcyclic : ∀ alpha : DeRhamCohomology
        (I := I) (M := (U ⊓ V : TopologicalSpace.Opens M)) (A := ℝ) 1,
      ∃ c : ℝ, alpha = c • generator)
    (hleft : ¬ Subsingleton
      (DeRhamCohomology (I := I) (M := U) (A := ℝ) 1)) :
    Subsingleton (DeRhamCohomology (I := I) (M := V) (A := ℝ) 1) := by
  letI : Nontrivial
      (DeRhamCohomology (I := I) (M := U) (A := ℝ) 1) :=
    not_subsingleton_iff_nontrivial.mp hleft
  rcases exists_ne
      (0 : DeRhamCohomology (I := I) (M := U) (A := ℝ) 1) with
    ⟨tau, htau⟩
  let rho := deRhamCohomologyRestrictionOfLE
    (I := I) (A := ℝ)
    (W := (U ⊓ V : TopologicalSpace.Opens M)) (V := U)
    inf_le_left 1
  have hrho_tau : rho tau ≠ 0 := by
    intro hrho_tau_zero
    rcases deRham_mayerVietoris_longExact (A := ℝ) I U V hcover with ⟨LES⟩
    let zeroV : DeRhamCohomology (I := I) (M := V) (A := ℝ) 1 := 0
    have hdiff :
        deRhamMayerVietorisDifference (I := I) (A := ℝ) U V 1
            (tau, zeroV) = 0 := by
      change rho tau -
        deRhamCohomologyRestrictionOfLE (I := I) (A := ℝ)
          (W := (U ⊓ V : TopologicalSpace.Opens M)) (V := V)
          inf_le_right 1 0 = 0
      rw [hrho_tau_zero]
      rw [(deRhamCohomologyRestrictionOfLE (I := I) (A := ℝ)
        (W := (U ⊓ V : TopologicalSpace.Opens M)) (V := V)
        inf_le_right 1).map_zero]
      exact sub_self
        (0 : DeRhamCohomology (I := I)
          (M := (U ⊓ V : TopologicalSpace.Opens M)) (A := ℝ) 1)
    rcases (LES.exact_restriction_difference 1 (tau, zeroV)).mp hdiff with
      ⟨ambient, hambient⟩
    have hambient_zero : ambient = 0 := Subsingleton.elim _ _
    have hpair : (tau, zeroV) =
        (0 : DeRhamCohomology (I := I) (M := U) (A := ℝ) 1 ×
          DeRhamCohomology (I := I) (M := V) (A := ℝ) 1) := by
      calc
        (tau, 0) = deRhamMayerVietorisRestriction
            (I := I) (A := ℝ) U V 1 ambient := hambient.symm
        _ = deRhamMayerVietorisRestriction
            (I := I) (A := ℝ) U V 1 0 := congrArg _ hambient_zero
        _ = 0 := by
          apply Prod.ext
          · exact (deRhamCohomologyRestrictionToOpen
              (I := I) (M := M) (A := ℝ) U 1).map_zero
          · exact (deRhamCohomologyRestrictionToOpen
              (I := I) (M := M) (A := ℝ) V 1).map_zero
    exact htau (congrArg Prod.fst hpair)
  rcases hcyclic (rho tau) with ⟨c, hc⟩
  have hc_ne : c ≠ 0 := by
    intro hc_zero
    apply hrho_tau
    rw [hc, hc_zero, zero_smul]
  apply deRhamH1_subsingleton_of_mayerVietoris_left_restriction_surjective
    (A := ℝ) I U V hcover
  intro alpha
  rcases hcyclic alpha with ⟨d, hd⟩
  refine ⟨(d * c⁻¹) • tau, ?_⟩
  rw [map_smul, hc, smul_smul]
  simpa [hc_ne] using hd.symm

set_option synthInstance.maxHeartbeats 100000 in
theorem deRhamConstantH0Class_sub_eq
    (I : ModelWithCorners ℝ E H) [IsManifold I ∞ M]
    (c d : ℝ) :
    deRhamConstantH0Class (I0 := I) (M0 := M) c -
        deRhamConstantH0Class (I0 := I) (M0 := M) d =
      deRhamConstantH0Class (I0 := I) (M0 := M) (c - d) := by
  simp only [deRhamConstantH0Class, ← map_sub]
  apply congrArg
    (DeRhamExactClosedForms (I := I) (M := M) (A := ℝ) 0).mkQ
  apply Subtype.ext
  apply DifferentialForm.ext
  intro x
  ext q
  rw [show q = (fun i : Fin 0 => nomatch i) from Subsingleton.elim _ _]
  simp [deRhamConstantZeroClosedForm, smoothRealFunctionToZeroForm,
    smoothRealConstantFunction]
  change c - d = c - d
  rfl

/-- The degree-one class obtained by applying the Mayer--Vietoris connecting
map to a degree-zero step class on the overlap. -/
noncomputable def deRhamTwoOpenStepConnectingClass
    (I : ModelWithCorners ℝ E H) [IsManifold I ∞ M]
    [FiniteDimensional ℝ E] [T2Space M] [SigmaCompactSpace M]
    (U V : TopologicalSpace.Opens M) (hcover : U ⊔ V = ⊤)
    (step : DeRhamCohomology (I := I)
      (M := (U ⊓ V : TopologicalSpace.Opens M)) (A := ℝ) 0) :
    DeRhamCohomology (I := I) (M := M) (A := ℝ) 1 :=
  deRhamMayerVietorisConnectingOfPartitionOfUnity (A := ℝ)
    I U V hcover 0 step

set_option synthInstance.maxHeartbeats 100000 in
set_option maxHeartbeats 800000 in
/--
%%handwave
name:
  The overlap step generates first cohomology
statement:
  Let \(M=U\cup V\), with
  \(H^1_{\mathrm{dR}}(U)=H^1_{\mathrm{dR}}(V)=0\).  Let
  \(s\in H^0_{\mathrm{dR}}(U\cap V)\) be such that every degree-zero overlap
  class is \(c+d s\) for some \(c,d\in\mathbb R\).  Then every
  \(\alpha\in H^1_{\mathrm{dR}}(M)\) has the form
  \[
    \alpha=d\,\partial[s]
  \]
  for some \(d\in\mathbb R\), where \(\partial\) is the Mayer--Vietoris
  connecting map.
proof:
  Exactness makes \(\alpha\) the connecting image of an overlap class.  Split
  that class as \(c+d s\); the constant part comes from \(U\), so its
  connecting image vanishes, while additivity and real linearity leave
  \(d\,\partial[s]\).
-/
theorem deRhamH1_eq_smul_twoOpenStepConnecting
    (I : ModelWithCorners ℝ E H) [IsManifold I ∞ M]
    [FiniteDimensional ℝ E] [T2Space M] [SigmaCompactSpace M]
    (U V : TopologicalSpace.Opens M) (hcover : U ⊔ V = ⊤)
    (hU1 : Subsingleton
      (DeRhamCohomology (I := I) (M := U) (A := ℝ) 1))
    (hV1 : Subsingleton
      (DeRhamCohomology (I := I) (M := V) (A := ℝ) 1))
    (step : DeRhamCohomology (I := I)
      (M := (U ⊓ V : TopologicalSpace.Opens M)) (A := ℝ) 0)
    (hdecomp : ∀ eta : DeRhamCohomology (I := I)
        (M := (U ⊓ V : TopologicalSpace.Opens M)) (A := ℝ) 0,
      ∃ c d : ℝ,
        eta = deRhamConstantH0Class (I0 := I)
            (M0 := (U ⊓ V : TopologicalSpace.Opens M)) c + d • step)
    (alpha : DeRhamCohomology (I := I) (M := M) (A := ℝ) 1) :
    ∃ d : ℝ,
      alpha = d • deRhamTwoOpenStepConnectingClass I U V hcover step := by
  letI := hU1
  letI := hV1
  let connecting :=
    deRhamMayerVietorisConnectingOfPartitionOfUnity (A := ℝ)
      I U V hcover 0
  have hrestriction :
      deRhamMayerVietorisRestriction (I := I) (A := ℝ)
          U V 1 alpha = 0 := by
    apply Prod.ext
    · exact Subsingleton.elim _ _
    · exact Subsingleton.elim _ _
  have hexact :=
    deRham_mayerVietoris_exact_connecting_restriction_of_partitionOfUnity
      (A := ℝ) I U V hcover 0
  have hrange : alpha ∈ Set.range connecting :=
    (hexact alpha).mp hrestriction
  rcases hrange with ⟨eta, heta⟩
  rcases hdecomp eta with ⟨c, d, hdecomp_eta⟩
  have hconstant_range :
      deRhamConstantH0Class (I0 := I)
          (M0 := (U ⊓ V : TopologicalSpace.Opens M)) c ∈
        Set.range
          (deRhamMayerVietorisDifference (I := I) (A := ℝ) U V 0) := by
    refine ⟨(deRhamConstantH0Class (I0 := I) (M0 := U) c, 0), ?_⟩
    change
      deRhamCohomologyRestrictionOfLE (I := I) (A := ℝ)
          (W := (U ⊓ V : TopologicalSpace.Opens M)) (V := U)
          inf_le_left 0
          (deRhamConstantH0Class (I0 := I) (M0 := U) c) -
        deRhamCohomologyRestrictionOfLE (I := I) (A := ℝ)
          (W := (U ⊓ V : TopologicalSpace.Opens M)) (V := V)
          inf_le_right 0 0 =
        deRhamConstantH0Class (I0 := I)
          (M0 := (U ⊓ V : TopologicalSpace.Opens M)) c
    rw [deRhamCohomologyRestrictionOfLE_constant]
    simp
  have hconstant_zero :
      connecting
          (deRhamConstantH0Class (I0 := I)
            (M0 := (U ⊓ V : TopologicalSpace.Opens M)) c) = 0 := by
    have hexact0 :=
      deRham_mayerVietoris_exact_difference_connecting_of_partitionOfUnity
        (A := ℝ) I U V hcover 0
    exact (hexact0 _).mpr hconstant_range
  refine ⟨d, ?_⟩
  calc
    alpha = connecting eta := heta.symm
    _ = connecting
        (deRhamConstantH0Class (I0 := I)
            (M0 := (U ⊓ V : TopologicalSpace.Opens M)) c + d • step) :=
      congrArg connecting hdecomp_eta
    _ = connecting
          (deRhamConstantH0Class (I0 := I)
            (M0 := (U ⊓ V : TopologicalSpace.Opens M)) c) +
        connecting (d • step) :=
      deRhamMayerVietorisConnectingOfPartitionOfUnity_add
        I U V hcover 0 _ _
    _ = 0 + d • connecting step := by
      have hsmul :=
        deRhamMayerVietorisConnectingOfPartitionOfUnity_smul
          I U V hcover 0 d step
      change connecting (d • step) = d • connecting step at hsmul
      rw [hconstant_zero, hsmul]
    _ = d • deRhamTwoOpenStepConnectingClass I U V hcover step := by
      simp [deRhamTwoOpenStepConnectingClass, connecting]

set_option synthInstance.maxHeartbeats 100000 in
set_option maxHeartbeats 800000 in
/--
%%handwave
name:
  A separating overlap step has nonzero connecting class
statement:
  Let \(M=U\cup V\), assume every class in
  \(H^0_{\mathrm{dR}}(U)\) and \(H^0_{\mathrm{dR}}(V)\) is constant, and let
  \(s\in H^0_{\mathrm{dR}}(U\cap V)\).  If \(s=1\) on a nonempty open set
  \(P\subseteq U\cap V\) and \(s=0\) on a nonempty open set
  \(N\subseteq U\cap V\), then the Mayer--Vietoris class
  \(\partial[s]\in H^1_{\mathrm{dR}}(M)\) is nonzero.
proof:
  If \(\partial[s]=0\), exactness writes \(s\) as the difference of
  restrictions of degree-zero classes on \(U\) and \(V\).  Those classes are
  constants \(c,d\), so restriction to \(P\) gives \(c-d=1\), whereas
  restriction to \(N\) gives \(c-d=0\), a contradiction.
-/
theorem deRhamTwoOpenStepConnectingClass_ne_zero
    (I : ModelWithCorners ℝ E H) [IsManifold I ∞ M]
    [FiniteDimensional ℝ E] [T2Space M] [SigmaCompactSpace M]
    (U V : TopologicalSpace.Opens M) (hcover : U ⊔ V = ⊤)
    (step : DeRhamCohomology (I := I)
      (M := (U ⊓ V : TopologicalSpace.Opens M)) (A := ℝ) 0)
    (hU0 : ∀ alpha : DeRhamCohomology (I := I) (M := U) (A := ℝ) 0,
      ∃ c : ℝ, alpha = deRhamConstantH0Class (I0 := I) (M0 := U) c)
    (hV0 : ∀ beta : DeRhamCohomology (I := I) (M := V) (A := ℝ) 0,
      ∃ d : ℝ, beta = deRhamConstantH0Class (I0 := I) (M0 := V) d)
    (P N : TopologicalSpace.Opens M)
    (hP : P ≤ (U ⊓ V : TopologicalSpace.Opens M))
    (hN : N ≤ (U ⊓ V : TopologicalSpace.Opens M))
    [Nonempty P] [Nonempty N]
    (hstepP : deRhamCohomologyRestrictionOfLE
        (I := I) (A := ℝ) hP 0 step =
      deRhamConstantH0Class (I0 := I) (M0 := P) 1)
    (hstepN : deRhamCohomologyRestrictionOfLE
        (I := I) (A := ℝ) hN 0 step =
      deRhamConstantH0Class (I0 := I) (M0 := N) 0) :
    deRhamTwoOpenStepConnectingClass I U V hcover step ≠ 0 := by
  intro hzero
  let connecting :=
    deRhamMayerVietorisConnectingOfPartitionOfUnity (A := ℝ)
      I U V hcover 0
  have hzero' : connecting step = 0 := by
    simpa [deRhamTwoOpenStepConnectingClass, connecting] using hzero
  have hexact :=
    deRham_mayerVietoris_exact_difference_connecting_of_partitionOfUnity
      (A := ℝ) I U V hcover 0
  have hrange : step ∈ Set.range
      (deRhamMayerVietorisDifference (I := I) (A := ℝ) U V 0) :=
    (hexact _).mp hzero'
  rcases hrange with ⟨⟨alpha, beta⟩, hab⟩
  rcases hU0 alpha with ⟨c, hc⟩
  rcases hV0 beta with ⟨d, hd⟩
  rw [hc, hd] at hab
  change
    deRhamCohomologyRestrictionOfLE (I := I) (A := ℝ)
        (W := (U ⊓ V : TopologicalSpace.Opens M)) (V := U)
        inf_le_left 0
        (deRhamConstantH0Class (I0 := I) (M0 := U) c) -
      deRhamCohomologyRestrictionOfLE (I := I) (A := ℝ)
        (W := (U ⊓ V : TopologicalSpace.Opens M)) (V := V)
        inf_le_right 0
        (deRhamConstantH0Class (I0 := I) (M0 := V) d) = step at hab
  rw [deRhamCohomologyRestrictionOfLE_constant,
    deRhamCohomologyRestrictionOfLE_constant,
    deRhamConstantH0Class_sub_eq] at hab
  have hpositive := congrArg
    (deRhamCohomologyRestrictionOfLE (I := I) (A := ℝ) hP 0) hab
  have hnegative := congrArg
    (deRhamCohomologyRestrictionOfLE (I := I) (A := ℝ) hN 0) hab
  rw [deRhamCohomologyRestrictionOfLE_constant, hstepP] at hpositive
  rw [deRhamCohomologyRestrictionOfLE_constant, hstepN] at hnegative
  have hcd_one : c - d = 1 :=
    deRhamConstantH0Class_injective hpositive
  have hcd_zero : c - d = 0 :=
    deRhamConstantH0Class_injective hnegative
  linarith

end

end JJMath.Manifold
